### ISSUE TITLE
[2.34] exception when payer attacks

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#107]
Data from CrashReporter:

map=foret (64x64)
sprites=[Perso=Zildo
Coords:(522.41583, 636.9532 0.0)
info=ZILDO
mvt=VIDE weapon=null name=carenda, 523.41583, 646.9532 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 445.0, 844.0 (SHADOW), 691.0, 540.0 (102 - bank 0), 648.0, 406.0 (STONE_HEAVY), Perso=pano
Coords:(552.0, 938.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(504.64453, 679.8282 11.048271) ==> (-21,32)
info=ENEMY
mvt=VIDE, 504.64453, 685.8282 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(489.0, 881.3499 0.0) ==> (489,867)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 489.0, 880.3499 (SHADOW), Perso=new
Coords:(282.8802, 699.7396 0.0) ==> (341,683)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 282.8802, 698.7396 (SHADOW), Perso=new
Coords:(492.0, 404.0482 0.0) ==> (492,429)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 492.0, 403.0482 (SHADOW), Perso=new
Coords:(471.74088, 330.0 0.0) ==> (457,330)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 471.74088, 329.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(522.41583, 636.9532 0.0)
info=ZILDO
mvt=VIDE weapon=null name=carenda, Perso=pano
Coords:(552.0, 938.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(504.64453, 679.8282 11.048271) ==> (-21,32)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(489.0, 881.3499 0.0) ==> (489,867)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(282.8802, 699.7396 0.0) ==> (341,683)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(492.0, 404.0482 0.0) ==> (492,429)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(471.74088, 330.0 0.0) ==> (457,330)
info=ENEMY
mvt=VIDE]
variables={nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2]}
lastdialog=Lugdunia Forest
Lugdunia Village - South. Polaky - Northwest.
Lugdunia
�Anselme�: Polaky has always been a friendly land, but indeed you must know that Aldoran and Farabrume have known years of turmoil together.
�Anselme�: Did you know that Alembrume consists of several kingdoms ? Our beautiful Aldoran in the South, Polaky is to the North, and the land of Farabrume is beyond that.
�Anselme�: Feel free to read the books, there is a lot to learn in them.
�Anselme�: Polaky has always been a friendly land, but indeed you must know that Aldoran and Farabrume have known years of turmoil together.
�Anselme�: Did you know that Alembrume consists of several kingdoms ? Our beautiful Aldoran in the South, Polaky is to the North, and the land of Farabrume is beyond that.
�Anselme�: Feel free to read the books, there is a lot to learn in them.
�Anselme�: Hello, my son, my name's Anselme. I'm the village Librarian.
�Hezia�: You need a Moon Necklace with 2 Half-moons in it and 50 gold coins ! That is my price.
�Hezia�: Hi boy ! My name is Hezia, I am the witch of the village. For 50 gold coins,  I can increase your Energy.
�Laura�: Thank you for sending my husband back ! This is for you : a Red Potion. You'll feel better when you drink it.
�Citizen�: Strangely, trees drop their leaves, though it's out of season.
�Citizen�: Try talking several times to the same people, it could be useful.
�Citizen�: You'd surely take something...
�???�: The guard at the south of the village is addicted to Milk. I swear.
�Citizen�: Let's drink another one ! hic ...
�Citizen�: Come on to my house and let's drink together...
�Charles�: What ? Laura is looking for me ? Whoops ! Thanks for the message. I got to go. 
�Citizen�: He tried to remove her belt....
�???�: The guard at the south of the village is addicted to Milk. I swear.
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at zildo.monde.sprites.persos.PersoPlayer.attack(PersoPlayer.java:334)
	at zildo.server.PlayerManagement.keyPressAttack(PlayerManagement.java:561)
	at zildo.server.PlayerManagement.handleCommon(PlayerManagement.java:174)
	at zildo.server.PlayerManagement.manageKeyboard(PlayerManagement.java:127)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:146)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by tchegito** [comment]
It seems player is attacking without any weapon in hand. Maybe he uses previous object which disappear, and another item should have become the current weapon. Or he doesn't have any ? But that sounds odd.

**Comment by tchegito** [comment]
Fixed in [2.36]

2 new UTs added

c4d29939775f52f3623dd2134d3f068e6584e3e5
