### ISSUE TITLE
[2.35] Exception in SpriteSorter (reported by player)

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#109]
Player is in the entrance of Nature Palace, just near Crystallion, as he was talking to him. He got flut in his hands.

map=sousbois4 (64x45)
sprites=[Perso=Zildo
Coords:(830.4135, 136.74536 0.0)
info=ZILDO
mvt=VIDE weapon=[FLUT,0] name=Roxy, 832.4135, 146.74536 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 832.4135, 136.74536 (SHADOW_SMALL), 691.0, 540.0 (102 - bank 0), Entity id=204
x=912.0
y=584.0
nSpr=164
visible=true, 616.0, 317.0 (12 - bank 5), Perso=new
Coords:(765.2767, 407.0 29.311193) ==> (1124,407)
info=NEUTRAL
mvt=VIDE, 765.2767, 413.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(400.68314, 350.0 26.927097) ==> (-100,350)
info=NEUTRAL
mvt=VIDE, 400.68314, 356.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=arsinoe
Coords:(430.0, 185.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=neptune
Coords:(559.0, 419.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=porphyre
Coords:(686.0, 418.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=crystallion
Coords:(835.0, 129.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=archibald
Coords:(670.0, 69.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), loc:0
431.0553, 192.1411 (PURPLE_FIREFLY), loc:1
846.41016, 137.80971 (PURPLE_FIREFLY), loc:2
555.34717, 438.20575 (PURPLE_FIREFLY), loc:3
693.7909, 434.58743 (PURPLE_FIREFLY), loc:4
675.39075, 82.0594 (PURPLE_FIREFLY)]
persos=[Perso=Zildo
Coords:(830.4135, 136.74536 0.0)
info=ZILDO
mvt=VIDE weapon=[FLUT,0] name=Roxy, Perso=new
Coords:(765.2767, 407.0 29.311193) ==> (1124,407)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(400.68314, 350.0 26.927097) ==> (-100,350)
info=NEUTRAL
mvt=VIDE, Perso=arsinoe
Coords:(430.0, 185.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=neptune
Coords:(559.0, 419.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=porphyre
Coords:(686.0, 418.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=crystallion
Coords:(835.0, 129.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=archibald
Coords:(670.0, 69.0 0.0)
info=NEUTRAL
mvt=VIDE]
variables={allowedDynamite=yes, Dizzie=[[DYNAMITE,1],15,5], nettleCount=-1, loc:34=0.0, loc:27=0.0, moneyStolen=178.0, loc:28=0.0, BilelIgorVillage=[[EMPTY_BAG,1],100,1],[[BLUEDROP,1],15,-1],[[DYNAMITE,1],100,0], loc:33=0.0, Carlo=[[MOON, 1], 800, 1]}
lastdialog=Sous bois des chênes
�Crystallion�: Comment ? Moi, Crystallion, le plus brave des Esprits de la Nature ? Tu m'appelles une luciole ?
�Arsinoe�: Une luciole ? Je suis Arsinoe, le plus érudit des Esprits de la Nature.
�Crystallion�: Comment ? Moi, Crystallion, le plus brave des Esprits de la Nature ? Tu m'appelles une luciole ?
�Porphyre�: Pas du tout ! Je suis Porphyre, le plus résistant des Esprits de la Nature.
�Neptune�: Ne t'inquiète pas, ton ignorance est naturelle. Je suis Neptune, le plus cosmique des Esprits de la Nature.
�Archibald�: Si tu veux, jeune rongeur. Appelle moi Archibald, le plus sage des Esprits de la Nature.
�Neptune�: Ne t'inquiète pas, ton ignorance est naturelle. Je suis Neptune, le plus cosmique des Esprits de la Nature.
�Porphyre�: Pas du tout ! Je suis Porphyre, le plus résistant des Esprits de la Nature.
�Crystallion�: Comment ? Moi, Crystallion, le plus brave des Esprits de la Nature ? Tu m'appelles une luciole ?
�Arsinoe�: Une luciole ? Je suis Arsinoe, le plus érudit des Esprits de la Nature.
�Roxy�: Je devrais aller voir ça de plus près.
�Roxy�: Il y a des lueurs dans plusieurs buissons. On dirait des lucioles !
�Roxy�: Je devrais essayer de l'atteindre pour trouver ces Esprits.
�Roxy�: Oh ! Ces murs en ruine ! Ce doit être le lieu sacré dont m'a parlé Isidore !
�Roxy�: Il est gentil, mais qu'est-ce qu'il est bavard !
�Isidore�: Pas de quoi, princesse !
�Roxy�: Entendu, je vais m'y rendre. C'est ma seule piste. Merci Isidore pour ton aide.
�Isidore�: Eux ? Non, pas du tout ! Ils sont inoffensifs. Juste un peu susceptibles. Mais l'intérieur du Palais, par contre, ruisselle de pièges.
�Roxy�: Et ils sont dangereux ces esprits ?
�Isidore�: Depuis toujours, ceux que l'on appelle les Esprits Anciens se promènent aux abords du Palais, protégeant la Nature environnante.
java.lang.ArrayIndexOutOfBoundsException: length=500; index=500
	at zildo.monde.sprites.utils.SpriteSorter.orderSpritesByBank(SpriteSorter.java:209)
	at zildo.client.SpriteDisplay.updateSpritesClient(SpriteDisplay.java:169)
	at zildo.client.ClientEngineZildo.renderFrame(ClientEngineZildo.java:179)
	at zildo.platform.opengl.AndroidOpenGLGestion.render(AndroidOpenGLGestion.java:406)
	at zildo.client.Client.render(Client.java:265)
	at zildo.client.Client.mainLoop(Client.java:225)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

**Comment by tchegito** [comment]
Reproduced ! It happens when dialog is displayed, and player is browsing compass menu, in "guide" part. Number of fonts exceeds 500 and BAM !

We need to separate fonts, maybe, to avoid to have all in one single line.

**Comment by tchegito** [comment]
Fixed in [2.37]

Now, compass menu is forbidden during a dialog ==> too much characters on screen !

39fa04207486bea2a0813ca4dcd72732bd189038
