### ISSUE TITLE
[2.36] Exception in actionExecutor (reported by player)

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#110]
map=prison (47x28)
sprites=[Perso=Zildo
Coords:(254.45229, 322.62506 0.0)
info=ZILDO
mvt=TOUCHE weapon=[SWORD,0] name=Maya, 255.45229, 332.62506 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 960.0, 345.0 (SHADOW), 220.22704, 180.88223 (105 - bank 0)]
persos=[Perso=Zildo
Coords:(254.45229, 322.62506 0.0)
info=ZILDO
mvt=TOUCHE weapon=[SWORD,0] name=Maya]
variables={nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=no, Dizzie=[[DYNAMITE, 1], 15, 20], moneyStolen=350.0, BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2]}
lastdialog=Lugdunia Prison
�Guard�: Don't try anything, boy. I'm watching you !
�Guard�: So, boy, you want to see a prisoner ? Just show me which door and I will open it for you.
�Guard�: All right, you can go in.
�Guard�: You can see a prisoner for 10 gold coins.
Lugdunia
�Charles�: I don't know what's going on, the ground is weird !
Desert of Valori - North. Lugdunia Village -  East.
�Paul�: If you're looking for my father, he said he was going into town.
�Christa�: Thank you again for helping me ! I've hired somebody to cut the bushes, from now on.
�Old lady�: You're looking for the forest ? It's just north of the village.
�Ritou�: I don't know what it is exactly, but my father does. You can find him in the tavern if you need to.
�Ritou�: The guard blocking the Castle has a chink in his armor, I know it.
�Old man�: Oh a visitor ! Don't pay attention to my wife, her head has been wandering a little !
�Old lady�: So you met the psychic ? You're surely not disappointed then !
Piochais Farm - West. Lumbermill - East. Castle of Trion - South.
�Viper�: And that is all I can see.
�Old lady�: I wish you good luck saving the Princess !
�Old lady�: Uhh, you're following the King's orders ? I'm so sorry !
Lamedur Brothers Lumbermill.
Clearing of the Oaks
Nature, Maya ! Be aware !
Maya !
java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.util.Point zildo.monde.sprites.persos.Perso.getTarget()' on a null object reference
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:287)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:197)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

Hero is in the prison, with just one half-drop. He asked guard to visit Igor, and during his visit, he's been attacked by black guard (that he chased before), or he can die from his own dynamite. Anyway, he's projected to the gate, triggering yellow guard to come back to its place.
=> player dies, all characters are removed
=> a running script ask to move and turn guard
=> NPE because he no longer exists

**Comment by tchegito** [comment]
It happens in "eleoforet2":
map=eleoforet2 (64x64)
sprites=[Perso=Zildo
Coords:(768.0, 664.0 0.0)
info=ZILDO
mvt=VIDE weapon=[FLUT,0] name=Roxy

We really need to check NULL value in this case. It could be more effective to fix potential scripts, because they are triggered on an unusual way.

**Comment by tchegito** [comment]
Fixed in [2.37]

Just added a NULL check in this case, cancelling the executed action.

10de64ff535a0f657b644077f91820f89a44ca87
