### ISSUE TITLE
[2.37] Exception in crash reporter

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#117]
special=We have an additional failure here !Attempt to invoke virtual method 'zildo.monde.map.Area zildo.server.MapManagement.getCurrentMap()' on a null object reference
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List zildo.monde.Game.getLastDialog()' on a null object reference
	at zildo.client.stage.TexterStage.(TexterStage.java:32)
	at zildo.client.gui.menu.CompassMenu$2.run(CompassMenu.java:25)
	at zildo.client.Client.mainLoop(Client.java:234)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Apparently, EngineZildo.mapManagement is null, and EngineZildo.game (from main exception).

This is quite hard to understand ... How can we be in compass menu without map and game managers initialized ?

**Comment by tchegito** [comment]
Another one, probably related: (07/03/2018)

version=v2.46
special=We have an additional failure here !java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.map.Area zildo.server.MapManagement.getCurrentMap()' on a null object reference
	at zildo.fwk.net.www.CrashReporter.addContext(CrashReporter.java:34)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:110)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
java.util.ConcurrentModificationException
	at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:62)
	at zildo.client.gui.GUIDisplay.drawConsoleMessages(GUIDisplay.java:332)
	at zildo.client.gui.GUIDisplay.draw(GUIDisplay.java:326)
	at zildo.client.ClientEngineZildo.renderFrame(ClientEngineZildo.java:220)
	at zildo.platform.opengl.AndroidOpenGLGestion.render(AndroidOpenGLGestion.java:406)
	at zildo.client.Client.render(Client.java:273)
	at zildo.client.Client.mainLoop(Client.java:233)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
