### ISSUE TITLE
[2.37] Exception in collision

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#121]
Happened in prison13:

java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.sprites.desc.EntityType zildo.monde.sprites.elements.Element.getEntityType()' on a null object reference
	at zildo.monde.sprites.elements.ElementArrow.getCollision(ElementArrow.java:170)
	at zildo.monde.sprites.elements.Element.manageCollision(Element.java:424)
	at zildo.monde.sprites.elements.Element.physicMoveWithCollision(Element.java:259)
	at zildo.monde.sprites.elements.Element.animate(Element.java:322)
	at zildo.monde.sprites.elements.ElementArrow.animateFlying(ElementArrow.java:114)
	at zildo.monde.sprites.elements.ElementArrow.animate(ElementArrow.java:83)
	at zildo.server.SpriteManagement.updateSprites(SpriteManagement.java:644)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:201)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Full details from crash reporter:
map=prison13 (20x15)
sprites=[Perso=Zildo
Coords:(304.0, 132.0 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=Paul , 305.0, 142.0 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 151.36786, 172.0092 (103 - bank 0), 393.0, 132.0 (SHADOW_SMALL), 394.0, 132.0 (ARROW_LEFT)]
persos=[Perso=Zildo
Coords:(304.0, 132.0 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=Paul ]
variables={loc:61=0.0, allowedDynamite=yes, Dizzie=[[DYNAMITE,1],15,0], nettleCount=-1, BOSS_turret_phase=1.0, moneyStolen=214.0, loc:60=0.0, BilelIgorVillage=[[DYNAMITE,1],100,0], loc:30=0.0, fishWater=6.0, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0, loc:31=0.0}
lastdialog=Lugdunia
Desert of Valori - North. Lugdunia Village -  East.
�Viper�: And that is all I can see.
Lugdunia Castle
�Paul �: It's just you and me, Dragon !
�Paul �: I need to go back in that Cave of the Flames, through the hole near the Thieves Camp.
Lugdunia Prison
�Maltus�: Of course, my King. Let us go immediately.
�King Trion�: Now Maltus, will you get me out of here ?
�King Trion�: Beware of him ! His reign of terror is not over yet.
�King Trion�: Fair enough, young Paul . Here it is.
�Paul �: Please, your Majesty. I need this key to find your scepter!
�King Trion�: That is quite normal, my young Paul . The area where it lives has been locked a long time ago. Today, I'm the only one to have the key to access it.
�Maltus�: You really have been there ?
�Paul �: The one under the Thieves Camp ? But I have already been there, and I didn't see any dragon.
�King Trion�: Ah ! It is a fearsome dragon ! It lives in the Cave of the Flames.
�Paul �: But I need it ! Where can I find this beast ?
�King Trion�: But in recent times, Aldoran's key lies in the belly of a beast, underground.
�King Trion�: Absolutely, Paul . There are 3 locks. In Ancient Times, each kingdom had a key.
�Paul �: What ? We need several keys to open this gate ?
�King Trion�: Desert ? Unfortunately, it's closed by an ancient gate. Each King of Aldoran used to have one of the keys.
�Paul �: The chief of the thieves told me to go at the Valori desert. The vulture should be there, who stole the scepter.
�King Trion�: You may escort me when I am okay. For now, do you have some clues to find back my daughter and our scepter ?

**Comment by tchegito** [comment]
Fixed in [2.39]

Timing was hard to reproduce !

af6cfc8bb9979f12f24be2d7f036c70b4660d5d5
