### ISSUE TITLE
[2.38] Exception in script execution (probably with turtle)

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#122]
Ruben experienced this one too. Here is details from crashreporter:

map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(405.68832, 586.9764 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=Lugdunum, 406.68832, 596.9764 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 602.0, 393.0 (SHADOW), 413.68137, 596.9764 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(836.10846, 298.1898 0.0) ==> (871,301)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW), 419.58377, 583.2436 (LEAF_GREEN), loc:4
118.43102, 72.09892 (216 - bank 3), 410.45078, 584.64374 (LEAF_GREEN), 409.9492, 585.15765 (LEAF_GREEN), 410.9792, 583.4927 (LEAF_GREEN), 421.8762, 586.3416 (LEAF_GREEN), 422.13095, 586.6921 (LEAF_GREEN)]
persos=[Perso=Zildo
Coords:(405.68832, 586.9764 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=Lugdunum, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(836.10846, 298.1898 0.0) ==> (871,301)
info=ENEMY
mvt=VIDE]
variables={loc:24=0.0, loc:23=0.0, allowedDynamite=yes, Dizzie=[[DYNAMITE,1],15,0], BOSS_turret_phase=0.0, nettleCount=60, loc:27=0.0, moneyStolen=252.0, loc:5=0.0, BilelIgorVillage=[[EMPTY_BAG,1],100,1],[[DYNAMITE,1],100,2], loc:4=0.0, loc:26=0.0, fishWater=6.0, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0, loc:2=1.0}
lastdialog=Foret argentée
�Perle�: Et d'autres ne réagissent qu'au bruit. C'est bizarre hein !
�Perle�: Tu as vu les tortues qui se promènent près de la rive ? Certaines fuient dès qu'on les approche.
�Perle�: Salut l'ami ! Est-ce que tu es une sorte de chevalier ?
�Vacto�: Le château est interdit de ce côté. On voit bien la ferme des Piochais plus loin, mais pour moi, c'est trop haut pour sauter.
�Vacto�: Parfois c'est pénible d'être tout seul ici. Mais nous sommes coincés dans cette Foret Argentée.
�Vacto�: Ah c'est toi Lugdunum. Je t'ai vu chez Eleoric.
�Eleoric�: Ramène m'en 50 feuilles, s'il te plait.
�Eleoric�: C'est une plante qui pousse un peu dans notre forêt, mais surtout vers le Palais de la Nature, plus au sud.
�Eleoric�: A présent, tout ce qu'il manque pour le remède du roi, ce sont des feuilles d'orties.
�Vacto�: Entendu, druide. A demain.
�Eleoric�: Merci Vacto, tu peux me laisser désormais.
�Eleoric�: A la bonne heure ! Il ne nous manque plus que des orties pour le remède du roi !
�Vacto�: J'ai ramené des graines d'ellébore, des larmes de chauve-souris et de l'obsidienne.
�Eleoric�: Bon, qu'as tu ramassé aujourd'hui ?
�Vacto�: Salut.
�Eleoric�: Voici Vacto, mon assistant.
�Vacto�: Bonjour druide, je reviens de la cueillette.
�Eleoric�: Entrez !
�Eleoric�: J'ai besoin de graines d'ellébore, des larmes de chauve-souris, des feuilles d'orties, et de l'obsidienne.
�Eleoric�: L'ennui, c'est que pour conconcter une potion contre le rhume des foins, il me faut beaucoup d'ingrédients.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at zildo.server.state.ScriptCall.(ScriptCall.java:26)
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:163)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:390)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:197)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by tchegito** [comment]
Noticeable things (maybe): we see thins in 'sprites' section:
loc:4
118.43102, 72.09892 (216 - bank 3), 

"loc:4" doesn't seem to be the sprite's name, but how can it be here ? Bank and index match with "Y" button displayed on the bottom right corner (or left, for left-handed), but never at this Y coordinate.

**Comment by tchegito** [comment]
Another time: (15/01/2018)

```
map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(455.70718, 526.72327 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=justice , 456.70718, 536.72327 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 469.0, 388.0 (SHADOW), 442.70718, 522.7155 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=new
Coords:(574.0, 318.0 0.0)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(842.0, 294.0 0.0) ==> (842,294)
info=ENEMY
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW), 648.07806, 485.8291 (SHADOW_MINUS), 648.07806, 487.8291 (NETTLE_LEAF), 647.0249, 484.5328 (SHADOW_MINUS), 647.0249, 486.5328 (NETTLE_LEAF), 635.8903, 486.31128 (SHADOW_MINUS), 635.8903, 488.31128 (NETTLE_LEAF), 595.74634, 485.5773 (SHADOW_MINUS), 595.74634, 487.5773 (NETTLE_LEAF), 640.62067, 489.98886 (SHADOW_MINUS), 640.62067, 491.98886 (NETTLE_LEAF), 462.25134, 518.38824 (LEAF_GREEN), 464.41733, 521.87885 (LEAF_GREEN), 465.3878, 523.2736 (LEAF_GREEN), 468.46286, 520.78033 (LEAF_GREEN)]
persos=[Perso=Zildo
Coords:(455.70718, 526.72327 0.0)
info=ZILDO
mvt=VIDE weapon=[MIDSWORD,0] name=justice , Perso=new
Coords:(574.0, 318.0 0.0)
info=ENEMY
mvt=VIDE, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(842.0, 294.0 0.0) ==> (842,294)
info=ENEMY
mvt=VIDE]
variables={loc:32=1.0, loc:98=0.0, moneyStolen=136.0, loc:20=0.0, loc:81=0.0, Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE,1],15,0], BOSS_turret_phase=1.0, loc:29=1.0, fishWater=6.0, loc:33=0.0, loc:31=0.0, allowedDynamite=yes, nettleCount=32, BilelIgorVillage=[[DYNAMITE,1],100,1], loc:12=1.0, bossFighting=0.0, loc:13=0.0, loc:80=0.0}
lastdialog=Silver forest
�Vacto�: I'm on my way, as soon as I can. Long time since I've seen Christa.
�Vacto�: What ? You know about a secret passage to reach the farm ?
�Vacto�: It is forbidden to enter the castle from this side. We can see the Piochais farm, but that's too high for me to jump.
�Vacto�: Sometime, I get bored, here alone. But we're stuck, in this Silver Forest.
�Vacto�: Ah that's you justice . I saw you at Eleoric's home.
�Eleoric�: Bring me 50 leaves, please.
�Eleoric�: This is a plant growing in our forest around here, but more specifically near the Palace of Nature, to the south.
�Eleoric�: Now, we have to find these nettle leaves.
�Vacto�: Very well, druid. See you tomorrow.
�Eleoric�: Thank you Vacto, you can leave now.
�Eleoric�: About time ! We are only missing nettle leaves for the King's remedy !
�Vacto�: I brought hellebore seeds, some bat tears and obsidian.
�Eleoric�: So, what did you found today ?
�Vacto�: Hi.
�Eleoric�: This is Vacto, my assistant.
�Vacto�: Greetings druid, I come back from the harvesting.
�Eleoric�: Come in !
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves and obsidian.
�Eleoric�: The thing is, to prepare a potion for hay fever, I need a lot of ingredients.
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves and obsidian.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at zildo.server.state.ScriptCall.(ScriptCall.java:26)
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:163)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:390)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:197)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

```

**Comment by tchegito** [comment]
Another one (16/02/2018):

```
map=sousbois7 (64x32)
sprites=[Perso=Zildo
Coords:(213.39923, 188.3263 0.0)
info=ZILDO
mvt=VIDE pv=10 weapon=[MIDSWORD,0] name=joel lasthit=null, 214.39923, 198.3263 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 210.0, 218.0 (SHADOW), 168.25621, 387.63016 (103 - bank 0), Perso=sacher
Coords:(96.0, 437.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 96.0, 434.0 (SHADOW), Perso=sacher2
Coords:(168.0, 180.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 165.0, 178.0 (SHADOW_LARGE), Perso=new
Coords:(326.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(730.0, 41.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(741.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(755.0, 51.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(761.0, 61.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(728.0, 63.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0)]
persos=[Perso=Zildo
Coords:(213.39923, 188.3263 0.0)
info=ZILDO
mvt=VIDE pv=10 weapon=[MIDSWORD,0] name=joel lasthit=null, Perso=sacher
Coords:(96.0, 437.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=sacher2
Coords:(168.0, 180.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(326.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(730.0, 41.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(741.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(755.0, 51.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(761.0, 61.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(728.0, 63.0 0.0)
info=ENEMY
mvt=VIDE pv=1]
variables={loc:14=0.0, loc:0=tortueSousbois7, allowedDynamite=yes, Dizzie=[[DYNAMITE,1],15,9], BOSS_turret_phase=1.0, nettleCount=17, loc:34=0.0, moneyStolen=311.0, loc:19=0.0, BilelIgorVillage=[[DYNAMITE,1],100,0], fishWater=6.0, loc:33=0.0, loc:12=1.0, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0}
scripts=2 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],fromActions[2 on [script self 17 , angle self 1 , loop ]],}
lastdialog=Silver forest
�Eleoric�: Bring me 50 leaves, please.
�Eleoric�: This is a plant growing in our forest around here, but more specifically near the Palace of Nature, to the south.
�Eleoric�: Now, we have to find these nettle leaves.
�Vacto�: Very well, druid. See you tomorrow.
�Eleoric�: Thank you Vacto, you can leave now.
�Eleoric�: About time ! We are only missing nettle leaves for the King's remedy !
�Vacto�: I brought hellebore seeds, some bat tears and obsidian.
�Eleoric�: So, what did you found today ?
�Vacto�: Hi.
�Eleoric�: This is Vacto, my assistant.
�Vacto�: Greetings druid, I come back from the harvesting.
�Eleoric�: Come in !
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves and obsidian.
�Eleoric�: The thing is, to prepare a potion for hay fever, I need a lot of ingredients.
Lugdunia Castle
�Irma�: If you can ever told my grandson to leave my house and live a life, that would relieve me so much.
�Irma�: I'd like to regain a little bit peace.
�Irma�: I live with my grandson in the Silver Birch Forest. But he refuses to leave since he works with that druid.
�Irma�: This park used to be highly frequented before. But since the castle has expanded, there are not much roads leading here anymore.
�Irma�: Well, it's not often I see new people around here !
Lugdunia Prison
�Joel�: All right, your Majesty ! I'm going to find her right now, and I bring you back the cure.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at zildo.server.state.ScriptCall.(ScriptCall.java:26)
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:168)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:204)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

```

**Comment by tchegito** [comment]
A track would be about saved games. Because local variables are saved. That's not a real need, and should be removed, but actually, if this is the cause of this, it should be proofed.

**Comment by tchegito** [comment]
Happened another time (still in sousbois7)

```
version=v2.55
map=sousbois7 (64x32)
sprites=[Perso=Zildo
Coords:(156.51637, 349.09512 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=damir lasthit=null, 157.51637, 359.09512 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 179.41455, 383.2111 (103 - bank 0), Perso=sacher
Coords:(96.0, 437.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 96.0, 434.0 (SHADOW), Perso=sacher2
Coords:(168.0, 180.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 165.0, 178.0 (SHADOW_LARGE), Perso=new
Coords:(730.0, 41.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(741.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(755.0, 51.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(761.0, 61.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(728.0, 63.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0)]
persos=[Perso=Zildo
Coords:(156.51637, 349.09512 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=damir lasthit=null, Perso=sacher
Coords:(96.0, 437.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=sacher2
Coords:(168.0, 180.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(730.0, 41.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(741.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(755.0, 51.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(761.0, 61.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(728.0, 63.0 0.0)
info=ENEMY
mvt=VIDE pv=1]
variables={fishWater=6.0, bossFighting=0.0, moneyStolen=163.0, loc:24=1.0, Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE,1],15,18], loc:26=0.0, BilelIgorVillage=[[EMPTY_BAG,1],100,1], BOSS_turret_phase=2.0, loc:0=tortueSousbois7, nettleCount=47, allowedDynamite=yes}
scripts=2 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],fromActions[2 on [script self 17 , angle self 1 , loop ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, forbid_dynamiteCell, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_cell1kill, prison5_cell2kill, prison5_bigrat2kill, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, waitIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4_left, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, getMidSword, meetEleo, eleoSpeak, eleoWaitForVacto, startGatherNettle, fermem2(7, 15), prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), voleursg3(3, 14), voleursg2(31, 24), voleursm2u(10, 7), allFishMinsk, prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet2(27, 52), sousbois5(18, 4), eleoforet1(57, 24), eleoforet1(29, 9), sousbois6(21, 20), sousbois6(39, 34), sousbois3(19, 4), sousbois3(14, 3), sousbois3(40, 30), sousbois3(39, 30), sousbois1(15, 28)]
lastdialog=Silver Forest
�Eleoric�: Bring me 50 leaves, please.
�Eleoric�: This is a plant growing in our forest around here, but more specifically near the Palace of Nature, to the south.
�Eleoric�: Now, we have to find these nettle leaves.
�Carlo�: Hi buddy. I have something very rare to sell. Are you interested?
�Eleoric�: Bring me 50 leaves, please.
�Eleoric�: This is a plant growing in our forest around here, but more specifically near the Palace of Nature, to the south.
�Eleoric�: Now, we have to find these nettle leaves.
�Vacto�: Very well, druid. See you tomorrow.
�Eleoric�: Thank you Vacto, you can leave now.
�Eleoric�: About time! We are only missing nettle leaves for the King's remedy!
�Vacto�: I brought hellebore seeds, some bat tears, and obsidian.
�Eleoric�: So, what did you find today?
�Vacto�: Hi.
�Eleoric�: This is Vacto, my assistant.
�Vacto�: Greetings druid, I've come back from harvesting.
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves, and obsidian.
�Eleoric�: Come in!
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves, and obsidian.
�Eleoric�: The thing is, to prepare a potion for hay fever, I need a lot of ingredients.
�Eleoric�: You are damir and come for a remedy? You knocked at the right door.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at zildo.server.state.ScriptCall.(ScriptCall.java:26)
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:168)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:224)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by tchegito** [comment]
Happened again 27/06/2019 (in 2.55, before deep changes in 2.56):

```
version=v2.55
map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(420.82812, 573.04895 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=[MIDSWORD,0] name=r2d2 lasthit=last hit by Perso=new
Coords:(667.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois3, 421.82812, 583.04895 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 409.79507, 582.0159 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=new
Coords:(696.6348, 159.44962 7.8484025) ==> (702,150)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 696.6348, 158.44962 (SHADOW), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(851.0, 192.07346 0.0) ==> (851,187)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(420.82812, 573.04895 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=[MIDSWORD,0] name=r2d2 lasthit=last hit by Perso=new
Coords:(667.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois3, Perso=new
Coords:(696.6348, 159.44962 7.8484025) ==> (702,150)
info=ENEMY
mvt=VIDE pv=2, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(851.0, 192.07346 0.0) ==> (851,187)
info=ENEMY
mvt=VIDE pv=2]
variables={loc:50=1.0, loc:52=0.0, moneyStolen=75.0, Dizzie=[[DYNAMITE,1],15,15], loc:54=0.0, loc:53=1.0, nettleCount=-1, loc:65=0.0, loc:64=0.0, BOSS_turret_phase=1.0, allowedDynamite=yes, bossFighting=0.0, BilelIgorVillage=[[EMPTY_BAG,1],100,0], loc:3=0.0, loc:2=1.0, fishWater=6.0, Carlo=[[MOON, 1], 800, 1]}
scripts=1 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, fermierperdu_ask, fermierperdu_bar, fermierperdu, fermierperdu_win, gardelaitier, gardelaitier_win, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm4(13, 3), trig_falcor, summonLeaf, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, forbid_dynamiteCell, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_bigrat2kill, prison5_button1, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, waitIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, getMidSword, prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), allFishMinsk, prison4r(9, 13), prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, polaky4(42, 23), prisonext(3, 7), prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet1(13, 20)]
lastdialog=Silver Forest
�Perle�: And some others stay if we remain silent. That's odd!
�Perle�: Did you see the turtles hanging around the river? Some of them flee as soon as we are close to them.
�Perle�: Hi my friend! Are you a sort of knight?
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Castle
�Irma�: If you can ever convince my grandson to leave my house and live a life, that would relieve me so much.
�Irma�: I'd like to regain a little bit of peace.
�Irma�: I live with my grandson in the Silver Birch Forest. But he refuses to leave since he works with that druid.
�Irma�: This park used to be highly frequented before. But since the castle has expanded, there are not many roads leading here anymore.
�Irma�: Well, it's not often I see new people around here!
Lugdunia Prison
�R2d2�: Alright, your Majesty! I'm going to find her right now and bring back the cure for you.
�King Trion�: Go through the door and down the stairs, then head to the west. The druid lives in the forest nearby.
�King Trion�: Ah! A lot of people believe she is a legend. But she really exists.
�R2d2�: Very well, your Highness. But how can I find her? I don't know anybody who ever met Eleoric.
�King Trion�: I would need a potion from Eleoric, the druid living west of the castle. She can heal all diseases.
�R2d2�: But what can I do to help, your Majesty?
�King Trion�: I've got a strong hay fever. I can hardly breathe.
�King Trion�: Since we lost the Scepter, Nature is upside-down. And aaaatchooo!
�King Trion�: Unfortunately, aaaatchooo! By now, I can't leave this bed.
�King Trion�: Excellent, r2d2. You did a good job.
�R2d2�: Yes, I defeated all of them, your Highness.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
	at zildo.server.state.ScriptCall.(ScriptCall.java:26)
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:168)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:224)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```
