### ISSUE TITLE
[2.40] Exception in map scrolling

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#125]
No crash report. Phone is: Samsung Galaxy S7 (herolte), 4096MB RAM, Android 7.0

java.lang.NullPointerException: 
  at zildo.server.MapManagement.shiftPreviousMap (MapManagement.java:823)
  at zildo.server.MapManagement.processChangingMap (MapManagement.java:701)
  at zildo.server.EngineZildo.renderEvent (EngineZildo.java:217)
  at zildo.client.stage.SinglePlayer.updateGame (SinglePlayer.java:157)
  at zildo.client.Client.mainLoop (Client.java:194)
  at com.alembrum.OpenGLRenderer.onDrawFrame (OpenGLRenderer.java:107)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1562)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1262)

**Comment by tchegito** [comment]
Found a trace from CrashReporter:

map=igorlily (64x28)
sprites=[Perso=Zildo
Coords:(1008.0, 186.0 0.0)
info=ZILDO
mvt=VIDE weapon=[SWORD,0] name=aku tidak , 1009.0, 196.0 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 153.0, 159.0 (SHADOW), 1001.0, 196.0 (103 - bank 0)]
persos=[Perso=Zildo
Coords:(1008.0, 186.0 0.0)
info=ZILDO
mvt=VIDE weapon=[SWORD,0] name=aku tidak , Perso=new
Coords:(226.0, 172.0 10.0)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(425.0, 221.0 10.0)
info=ENEMY
mvt=VIDE, Perso=new
Coords:(743.0, 408.0 10.0)
info=ENEMY
mvt=VIDE]
variables={nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], moneyStolen=322.0, BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2]}
lastdialog=Lugdunia
�Gerard�: See you soon, aku tidak .
�Robert�: Please let me get some rest. I'll see you later.
�Robert�: If you're looking for my brother, Gerard, he's in his home.
�Robert�: Hi aku tidak . As you can see, I'm exhausted from my work. There is always more work to do around here !
�Petula�: Rumor has it that weird monsters are prowling around the Fishermen Island.
�Old lady�: That's awful, what have they done with our King ! What will happen to us now ?
�Old lady�: So you met the psychic ? You're surely not disappointed then !
�Old man�: Oh a visitor ! Don't pay attention to my wife, her head has been wandering a little !
�Ritou�: I don't know what it is exactly, but my father does. You can find him in the tavern if you need to.
�Ritou�: The guard blocking the Castle has a chink in his armor, I know it.
�Hezia�: You need a Moon Necklace with 2 Half-moons in it and 50 gold coins ! That is my price.
Your two Half-moons have combined and you will now receive an additional Energy drop !
�Hezia�: Now, watch the show.
�Hezia�: Thanks for your money !
�Hezia�: Hi boy ! My name is Hezia, I am the witch of the village. For 50 gold coins,  I can increase your Energy.
�Anselme�: Polaky has always been a friendly land, but indeed you must know that Aldoran and Farabrume have known years of turmoil together.
�Anselme�: Did you know that Alembrume consists of several kingdoms ? Our beautiful Aldoran in the South, Polaky is to the North, and the land of Farabrume is beyond that.
�Anselme�: Feel free to read the books, there is a lot to learn in them.
�Anselme�: Hello, my son, my name's Anselme. I'm the village Librarian.
�Maltus�: I hope that Black Guards won't find us here.
java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.util.Point zildo.monde.map.Area.getNextMapOffset(zildo.monde.map.Area, zildo.monde.util.Angle, boolean)' on a null object reference
	at zildo.server.MapManagement.shiftPreviousMap(MapManagement.java:823)
	at zildo.server.MapManagement.processChangingMap(MapManagement.java:701)
	at zildo.server.EngineZildo.renderEvent(EngineZildo.java:217)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:157)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by tchegito** [comment]
[Fixed in 2.41]

Thanks to this report, I did reproduce the situation, without the NPE, but it should be the same.

Hero could navigate on the leaf so it touches the border and stop. Then he walks on it to switch map, and this leads to switch back-and-forth.

83c1771bb90086d875e2150e9ad0a47cbf529d34
