### ISSUE TITLE
[2.40] Exception reading saved game

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#126]
Example from crash reporter (happens when displaying saved games):

java.lang.RuntimeException: Unable to read save.z4
	at com.alembrum.AndroidReadingFile.(AndroidReadingFile.java:67)
	at com.alembrum.AndroidReadingFile.openPrivate(AndroidReadingFile.java:84)
	at com.alembrum.AndroidFileUtil.openPrivateFile(AndroidFileUtil.java:61)
	at zildo.client.PlatformDependentPlugin.openPrivateFile(PlatformDependentPlugin.java:156)
	at zildo.client.gui.menu.SaveGameMenu.findSavegame(SaveGameMenu.java:210)
	at zildo.client.gui.menu.SaveGameMenu.(SaveGameMenu.java:70)
	at zildo.client.gui.menu.InGameMenu$2.run(InGameMenu.java:56)
	at zildo.client.Client.mainLoop(Client.java:242)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1524)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
Caused by: java.lang.IndexOutOfBoundsException: offset=0, count=-1, length=4000
	at java.nio.Buffer.checkPutBounds(Buffer.java:185)
	at java.nio.ReadWriteHeapByteBuffer.put(ReadWriteHeapByteBuffer.java:110)
	at com.alembrum.AndroidReadingFile.(AndroidReadingFile.java:59)
	... 10 more

A file seems corrupt. We need to handle this by at least displaying an error, instead of crashing the game.

**Comment by tchegito** [comment]
[Fixed in 2.41]

2195e924e5e58f6a25ef66f0bfc823cae04a1fa6
