### ISSUE TITLE
[2.41] Runtime Exception: 'who' or 'what' attribute missing

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#127]
Same symptom as issue #45 but happened again !

Here is 2 details from CrashReporter:

**1) 28/10/2017**: when hero comes in polaky's cave and barrel has to move (exactly like issue #45 

map=polakyg (37x25)
sprites=[Perso=Zildo
Coords:(544.0, 296.0 0.0)
info=ZILDO
mvt=TOUCHE weapon=[SWORD,0] name=Glacius, 545.0, 306.0 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 691.0, 540.0 (102 - bank 0)]
persos=[Perso=Zildo
Coords:(544.0, 296.0 0.0)
info=ZILDO
mvt=TOUCHE weapon=[SWORD,0] name=Glacius]
variables={BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2], Carlo=[[MOON, 1], 800, 1], nettleCount=-1, Dizzie=[[DYNAMITE, 1], 15, 20], allowedDynamite=yes}
lastdialog=Polaky Caves
�Gamin�: Hellosky ! I think there's a secret passage heresky !
�Cyclosky�: Resistance shall overcome !
�Gabriel�: Beware young man, and remember Gabriel's advice, never face a black guard alone.
�Gabriel�: After that, I joined the Polaky Resistance. You have found your way to our meeting room.
�Gabriel�: Since then, my brothers have been killed by all these Marquese guards. I don't get how the Marquese could give such an order after being so good to us in the past.
�Gabriel�: I had to leave my homeland after vampire Rastael surrounded our holy Church. I had to flee with my family, and fate had led us to Polaky. 
�Gabriel�: How did you get in here, young boy ? At your age, your intentions must certainly be innocent. You have no fear.
�???�: What are you doing here, son ? This is not a place for kids. You should return home.
Polaky
�Ritasky�: Do you have some news of my husband ?
�Ritasky�: My husband Gerarsky has been gone for a week on Marquese Ribinsky's orders. I still haven't seen him. Please Glacius, try to learn what's become of him.
�Ritasky�: Over the past little while, strangers arrived in the city. Citizens started disappearing. I don't see anyone outside, except those frightening guards.
�Ritasky�: Hi young Glacius. My name's Ritasky. You should have noticed that the Marquese's palace is under watchful eye these days. I don't get it.
�Sissisky�: Anyway, I'm sad now.
�Sissisky�: Do you want to play with me ?
�Sissisky�: Hi little boy ! I'm the daughter of Gerarsky, the blacksmith. Do you know where my father is ?
�Ritasky�: Do you have some news of my husband ?
�Ritasky�: My husband Gerarsky has been gone for a week on Marquese Ribinsky's orders. I still haven't seen him. Please Glacius, try to learn what's become of him.
�Ritasky�: Over the past little while, strangers arrived in the city. Citizens started disappearing. I don't see anyone outside, except those frightening guards.
�Ritasky�: Hi young Glacius. My name's Ritasky. You should have noticed that the Marquese's palace is under watchful eye these days. I don't get it.
�Sofiasky�: Unfortunately, I can't say more.
java.lang.RuntimeException: We need valid 'who' or 'what' attribute in action pos barrel1 (0, 16) 
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:163)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:197)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

-----------------

**2) 18/11/2017**: cutscene just at the beginning of second episode

map=promenade2 (64x32)
sprites=[Perso=Zildo
Coords:(868.221, 7.6984854 0.0) ==> (867,8)
info=ZILDO
mvt=VIDE weapon=[SWORD,0] name=Griffin, 869.221, 17.698486 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 716.0, 601.0 (SHADOW), 431.21866, 240.27094 (103 - bank 0), Perso=new
Coords:(543.0023, 382.0 42.97676) ==> (-100,382)
info=NEUTRAL
mvt=VIDE, 543.0023, 388.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(640.002, 489.0 42.97676) ==> (-100,489)
info=NEUTRAL
mvt=VIDE, 640.002, 495.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(812.0016, 252.0 42.97676) ==> (-100,252)
info=NEUTRAL
mvt=VIDE, 812.0016, 258.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(352.0033, 134.0 42.97676) ==> (-100,134)
info=NEUTRAL
mvt=VIDE, 352.0033, 140.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(840.0016, 421.0 42.97676) ==> (-100,421)
info=NEUTRAL
mvt=VIDE, 840.0016, 427.0 (80 - bank 0), 0.0, -12.0 (SHADOW_SMALL), Perso=new
Coords:(585.2272, 287.1675 3.3000002) ==> (569,294)
info=NEUTRAL
mvt=VIDE, 0.0, 0.0 (80 - bank 0), 585.2272, 286.1675 (SHADOW), Perso=emissaire
Coords:(424.0, 255.0 0.0) ==> (370,255)
info=null
mvt=null, 0.0, 0.0 (80 - bank 0), 418.0, 258.0 (116 - bank 2), 424.0, 255.0 (JAR)]
persos=[Perso=Zildo
Coords:(868.221, 7.6984854 0.0) ==> (867,8)
info=ZILDO
mvt=VIDE weapon=[SWORD,0] name=Griffin, Perso=new
Coords:(543.0023, 382.0 42.97676) ==> (-100,382)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(640.002, 489.0 42.97676) ==> (-100,489)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(812.0016, 252.0 42.97676) ==> (-100,252)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(352.0033, 134.0 42.97676) ==> (-100,134)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(840.0016, 421.0 42.97676) ==> (-100,421)
info=NEUTRAL
mvt=VIDE, Perso=new
Coords:(585.2272, 287.1675 3.3000002) ==> (569,294)
info=NEUTRAL
mvt=VIDE, Perso=emissaire
Coords:(424.0, 255.0 0.0) ==> (370,255)
info=null
mvt=null]
variables={nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2]}
lastdialog=Lugdunia Forest
�Griffin�: Hold on !
Clearing of the Oaks
Nature, Griffin ! Be aware !
Griffin !
Nature, Griffin ! Be aware !
Griffin !
Nature, Griffin ! Be aware !
Griffin !
Nature, Griffin ! Be aware !
Griffin !
�Guard�: I must stay and search these bushes. You ! Griffin ! Follow this Agent of Darkness !
�Griffin�: What about the bandit ?
�Guard�: The King has ordered me to bring the Princess back safely. I must find her, no matter the cost !
�Guard�: Come back ! Bandit !
�Guard�: She ran away !
�Guard�: Princess Roxy !!!
�Princess Roxy�: Well ... I don't know. It's ... huh
�Guard�: Thank Helios ! Are you okay ?
�Princess Roxy�: Grand-pa ? Is that you ?
�Bandit�: I'm going to make her drink the potion my master gave me.
�Guard�: So wake her up ! Quick !
java.lang.RuntimeException: We need valid 'who' or 'what' attribute in action moveTo tony (0, -12) 
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:163)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:197)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by tchegito** [comment]
Fixed in [2.42]

Hero was collided during a map fade. For the second one, it has been fixed by adding a stump between maps.

85972e234d614644f73f7047a9c37bec8b7f6c3c
