### ISSUE TITLE
[2.43] ActivityNotFoundException

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#131]
A failure happened inside CrashReporter:

special=We have an additional failure here !null
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://www.alembrume.fr flg=0x10000000 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1663)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1431)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1274)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1256)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:330)
	at com.alembrum.AndroidFileUtil.openLink(AndroidFileUtil.java:123)
	at zildo.client.PlatformDependentPlugin.openLink(PlatformDependentPlugin.java:147)
	at zildo.client.gui.menu.StartMenu$2.run(StartMenu.java:76)
	at zildo.client.Client.mainLoop(Client.java:242)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

It seems to be a lack of exeception catch in onCreate() method in Activity:
https://stackoverflow.com/questions/3533370/android-activity-not-found-exception

**Comment by tchegito** [comment]
Fixed in 2.44 (just a try/catch block added to understand where it crashes in onCreate() method)

e5df84cb29b007def11994f4480625276613d05c

**Comment by tchegito** [comment]
This happens where there is no browser available to handle the intent.

We need to check if one is available and display message in this case to avoid a crash.
