### ISSUE TITLE
[2.46] Unable to execute script

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#142]
version=v2.46
map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(494.0296, 612.0952 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=Emonk lasthit=last hit by Perso=new
Coords:(712.59, 145.18752 6.9556065) ==> (722,162)
info=ENEMY
mvt=VIDE pv=2 on sousbois3, 495.0296, 622.0952 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 427.18625, 618.6564 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(800.67566, 240.0 0.0) ==> (758,240)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(494.0296, 612.0952 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=Emonk lasthit=last hit by Perso=new
Coords:(712.59, 145.18752 6.9556065) ==> (722,162)
info=ENEMY
mvt=VIDE pv=2 on sousbois3, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(800.67566, 240.0 0.0) ==> (758,240)
info=ENEMY
mvt=VIDE pv=2]
variables={loc:61=0.0, loc:0=1.0, allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], loc:53=0.0, BOSS_turret_phase=1.0, nettleCount=-1, loc:1=0.0, moneyStolen=334.0, loc:60=0.0, loc:55=0.0, loc:54=0.0, BilelIgorVillage=[[DYNAMITE,1],100,0], fishWater=6.0, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0}
scripts=1 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, voyante, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, v3_crate, voleursm4_hiddenbutton, voleursm4_button, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, forbid_dynamiteCell, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_bigrat2kill, prison5_button1, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, waitIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4_left, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, getMidSword, fermem2(7, 15), prisonext(40, 40), trip_polaky, foret(36, 30), polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), voleursg3(3, 14), voleursg2(31, 24), voleursm2u(10, 7), voleurscave(3, 32), voleurscave(48, 5), voleurscave(48, 8), voleurscave(44, 8), voleurscave(44, 5), voleursm3(8, 8), allFishMinsk, prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet1(57, 24)]
lastdialog=Silver forest
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Castle
�Irma�: If you can ever told my grandson to leave my house and live a life, that would relieve me so much.
�Irma�: I'd like to regain a little bit peace.
�Irma�: I live with my grandson in the Silver Birch Forest. But he refuses to leave since he works with that druid.
�Irma�: This park used to be highly frequented before. But since the castle has expanded, there are not much roads leading here anymore.
�Irma�: Well, it's not often I see new people around here !
Silver forest
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Prison
�Emonk�: All right, your Majesty ! I'm going to find her right now, and I bring you back the cure.
�King Trion�: Through the door down of these stairs, head to the west. The druid lives in the forest nearby.
�Emonk�: Not yet, unfortunately, your Highness.
�King Trion�: Did you bring back the cure that I need, young Emonk ?
�Emonk�: All right, your Majesty ! I'm going to find her right now, and I bring you back the cure.
�King Trion�: Through the door down of these stairs, head to the west. The druid lives in the forest nearby.
�Emonk�: Not yet, unfortunately, your Highness.
�King Trion�: Did you bring back the cure that I need, young Emonk ?
�Emonk�: All right, your Majesty ! I'm going to find her right now, and I bring you back the cure.
�King Trion�: Through the door down of these stairs, head to the west. The druid lives in the forest nearby.
�Emonk�: Not yet, unfortunately, your Highness.
�King Trion�: Did you bring back the cure that I need, young Emonk ?
�Emonk�: All right, your Majesty ! I'm going to find her right now, and I bring you back the cure.
java.lang.RuntimeException: Scene 1.0 doesn't exist !
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:175)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:204)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1557)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)

**Comment by tchegito** [comment]
Another one:

Happened at date '2018-09-12' \n

version=v2.54
map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(475.00604, 625.5702 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=Lord Aizen lasthit=last hit by Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois7, 475.00604, 635.5702 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 361.0, 165.0 (SHADOW), 641.4293, 518.99536 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=new
Coords:(722.301, 144.15823 6.9788065) ==> (717,141)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 722.301, 143.15823 (SHADOW), Perso=new
Coords:(667.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(705.0, 57.0 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(836.21277, 227.2153 0.0) ==> (824,215)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(475.00604, 625.5702 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[MIDSWORD,0] name=Lord Aizen lasthit=last hit by Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois7, Perso=new
Coords:(722.301, 144.15823 6.9788065) ==> (717,141)
info=ENEMY
mvt=VIDE pv=2, Perso=new
Coords:(667.0, 52.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(705.0, 57.0 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(836.21277, 227.2153 0.0) ==> (824,215)
info=ENEMY
mvt=VIDE pv=2]
variables={Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE,1],15,18], moneyStolen=102.0, BOSS_turret_phase=2.0, fishWater=6.0, bossFighting=0.0, loc:75=0.0, allowedDynamite=yes, loc:74=0.0, loc:72=1.0, BilelIgorVillage=[[EMPTY_BAG,1],100,0],[[DYNAMITE,1],100,2], loc:1=0.0, nettleCount=-1, loc:0=1.0}
scripts=1 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, voyante, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm4(13, 3), trig_falcor, voleursm4_hiddenbutton, voleursm4_button, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_bigrat2kill, prison5_button1, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), zildoAccessIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, getMidSword, fermem2(7, 15), prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, foret(36, 30), voleursg1(18, 4), voleurscave(3, 32), voleurscave(44, 5), voleurscave(48, 5), voleurscave(48, 8), voleurscave(44, 8), allFishMinsk, prison4r(9, 13), prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet1(13, 20)]
lastdialog=Silver Forest
�Perle�: And some others stay if we remain silent. That's odd!
�Perle�: Did you see the turtles hanging around the river? Some of them flee as soon as we are close to them.
�Perle�: Hi my friend! Are you a sort of knight?
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Castle
�Irma�: If you can ever convince my grandson to leave my house and live a life, that would relieve me so much.
�Irma�: I'd like to regain a little bit of peace.
�Irma�: I live with my grandson in the Silver Birch Forest. But he refuses to leave since he works with that druid.
�Irma�: This park used to be highly frequented before. But since the castle has expanded, there are not many roads leading here anymore.
�Irma�: Well, it's not often I see new people around here!
Lugdunia Prison
�Lord Aizen�: Alright, your Majesty! I'm going to find her right now and bring back the cure for you.
�King Trion�: Go through the door and down the stairs, then head to the west. The druid lives in the forest nearby.
�King Trion�: Ah! A lot of people believe she is a legend. But she really exists.
�Lord Aizen�: Very well, your Highness. But how can I find her? I don't know anybody who ever met Eleoric.
�King Trion�: I would need a potion from Eleoric, the druid living west of the castle. She can heal all diseases.
�Lord Aizen�: But what can I do to help, your Majesty?
�King Trion�: I've got a strong hay fever. I can hardly breathe.
�King Trion�: Since we lost the Scepter, Nature is upside-down. And aaaatchooo!
�King Trion�: Unfortunately, aaaatchooo! By now, I can't leave this bed.
�King Trion�: Excellent, Lord Aizen. You did a good job.
�Lord Aizen�: Yes, I defeated all of them, your Highness.
java.lang.RuntimeException: Scene 1.0 doesn't exist !
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:175)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:224)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:110)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1523)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by tchegito** [comment]
Another one: (08/06/2019)

version=v2.55
map=sousbois3 (64x45)
sprites=[Perso=Zildo
Coords:(435.62915, 580.47705 0.0)
info=ZILDO
mvt=VIDE pv=2 weapon=[MIDSWORD,0] name=Chara lasthit=null, 436.62915, 590.47705 (97 - bank 0), 691.0, 540.0 (83 - bank 0), 313.0, 147.0 (SHADOW), 422.62915, 574.94574 (103 - bank 0), 503.0, 157.0 (LAUNCHER1), 397.0, 581.0 (STONE_HEAVY), Perso=new
Coords:(704.9154, 160.63611 8.731254) ==> (722,146)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 704.9154, 159.63611 (SHADOW), Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 468.0, 569.0 (SHADOW_LARGE), Perso=new
Coords:(823.6421, 272.63943 0.0) ==> (850,291)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 0.0, 0.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(435.62915, 580.47705 0.0)
info=ZILDO
mvt=VIDE pv=2 weapon=[MIDSWORD,0] name=Chara lasthit=null, Perso=new
Coords:(704.9154, 160.63611 8.731254) ==> (722,146)
info=ENEMY
mvt=VIDE pv=2, Perso=sacher
Coords:(471.0, 571.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(823.6421, 272.63943 0.0) ==> (850,291)
info=ENEMY
mvt=VIDE pv=2]
variables={loc:0=1.0, Dizzie=[[DYNAMITE,1],15,11], allowedDynamite=yes, BilelIgorVillage=[[EMPTY_BAG,1],100,1],[[DYNAMITE,1],100,2], fishWater=6.0, BOSS_turret_phase=1.0, nettleCount=-1, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0, loc:1=0.0, moneyStolen=117.0}
scripts=1 scripts running {[fromActions[2 on [script self 17 , angle self 1 , loop ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, v3_crate, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, forbid_dynamiteCell, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_bigrat2kill, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, waitIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4_left, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, getMidSword, prisonext(40, 40), trip_polaky, polaky3(2, 7), foret(36, 30), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), voleursg3(3, 14), voleursg2(31, 24), voleursm2u(10, 7), voleursm3(8, 8), allFishMinsk, prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet1(13, 20)]
lastdialog=Silver Forest
�Perle�: Did you see the turtles hanging around the river? Some of them flee as soon as we are close to them.
�Perle�: Hi my friend! Are you a sort of knight?
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Prison
�Chara�: Alright, your Majesty! I'm going to find her right now and bring back the cure for you.
�King Trion�: Go through the door and down the stairs, then head to the west. The druid lives in the forest nearby.
�Chara�: Not yet, unfortunately, your Highness.
�King Trion�: Did you bring back the cure that I need, young Chara?
�Chara�: Alright, your Majesty! I'm going to find her right now and bring back the cure for you.
�King Trion�: Go through the door and down the stairs, then head to the west. The druid lives in the forest nearby.
�Chara�: Not yet, unfortunately, your Highness.
�King Trion�: Did you bring back the cure that I need, young Chara?
�Chara�: Alright, your Majesty! I'm going to find her right now and bring back the cure for you.
�King Trion�: Go through the door and down the stairs, then head to the west. The druid lives in the forest nearby.
�King Trion�: Ah! A lot of people believe she is a legend. But she really exists.
�Chara�: Very well, your Highness. But how can I find her? I don't know anybody who ever met Eleoric.
�King Trion�: I would need a potion from Eleoric, the druid living west of the castle. She can heal all diseases.
�Chara�: But what can I do to help, your Majesty?
�King Trion�: I've got a strong hay fever. I can hardly breathe.
�King Trion�: Since we lost the Scepter, Nature is upside-down. And aaaatchooo!
�King Trion�: Unfortunately, aaaatchooo! By now, I can't leave this bed.
java.lang.RuntimeException: Scene 1.0 doesn't exist !
	at zildo.server.state.ScriptManagement.execute(ScriptManagement.java:175)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:393)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:224)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1608)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1299)
