### ISSUE TITLE
NPE in dialogManagement

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#145]
Looks like an old one, but still present !

version=v2.48
map=preintro (40x40)
sprites=[Perso=Zildo
Coords:(160.0, 120.0 0.0)
info=ZILDO
mvt=VIDE pv=6 weapon=null name=@ juye4 lasthit=null, 161.0, 130.0 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 691.0, 540.0 (102 - bank 0)]
persos=[Perso=Zildo
Coords:(160.0, 120.0 0.0)
info=ZILDO
mvt=VIDE pv=6 weapon=null name=@ juye4 lasthit=null]
variables={Dizzie=[[DYNAMITE, 1], 15, 20], BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2], allowedDynamite=yes, Carlo=[[MOON, 1], 800, 1]}
scripts=1 scripts running {[preintro[12 on [music Story , fadeOut , map preintro , fadeIn , speak camera preintro.0 , speak camera preintro.1 , speak camera preintro.2 , speak camera preintro.3 , pos camera (0, 0) , pos zildo (320, 120) , moveTo zildo (160, 120) , angle zildo 2 , speak camera preintro.4 , speak camera preintro.5 , actions, speak camera preintro.6 , speak camera preintro.7 , actions, wait 100 , angle roxy 1 , animation (160, 120) HEARTS , animation (100, 120) HEARTS , speak camera preintro.8 , speak camera preintro.9 , speak camera preintro.10 , exec intro ]],}
quests=[]
lastdialog=
   Aucun dialogue enregistré pour l'instant !
java.lang.NullPointerException
	at zildo.monde.dialog.DialogManagement.continueDialog(DialogManagement.java:201)
	at zildo.monde.dialog.DialogManagement.goOnDialog(DialogManagement.java:233)
	at zildo.server.PlayerManagement.keyPressAction(PlayerManagement.java:427)
	at zildo.server.PlayerManagement.handleCommon(PlayerManagement.java:167)
	at zildo.server.PlayerManagement.manageKeyboard(PlayerManagement.java:124)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:153)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by tchegito** [comment]
Due to a character who should have been forbidden in the hero's name: "@"

Fixed in 2.49

33d546a52991671046aac35cd1d4f34a3449fc94
