### ISSUE TITLE
ConcurrentModificationException in console messages

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#147]
Happened 07/03/2018:

```
version=v2.46
special=We have an additional failure here !java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.map.Area zildo.server.MapManagement.getCurrentMap()' on a null object reference
	at zildo.fwk.net.www.CrashReporter.addContext(CrashReporter.java:34)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:110)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
java.util.ConcurrentModificationException
	at java.util.AbstractList$SimpleListIterator.next(AbstractList.java:62)
	at zildo.client.gui.GUIDisplay.drawConsoleMessages(GUIDisplay.java:332)
	at zildo.client.gui.GUIDisplay.draw(GUIDisplay.java:326)
	at zildo.client.ClientEngineZildo.renderFrame(ClientEngineZildo.java:220)
	at zildo.platform.opengl.AndroidOpenGLGestion.render(AndroidOpenGLGestion.java:406)
	at zildo.client.Client.render(Client.java:273)
	at zildo.client.Client.mainLoop(Client.java:233)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

**Comment by tchegito** [comment]
Fixed in 2.49

Used a CopyOnWriteArrayList instead of Stack

c7095a4cd367966f7c56645f6edb7b34ff016e7b
