### ISSUE TITLE
Unable to save game: no space left on device

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#157]
Happened once September 1st:

```
java.lang.RuntimeException: Unable to write saves/save.z7 !
	at zildo.fwk.file.EasyWritingFile.saveFile(EasyWritingFile.java:53)
	at zildo.client.gui.menu.SaveGameMenu.saveGame(SaveGameMenu.java:158)
	at zildo.client.gui.menu.SaveGameMenu.access$1(SaveGameMenu.java:154)
	at zildo.client.gui.menu.SaveGameMenu$2$1.run(SaveGameMenu.java:89)
	at zildo.client.Client.mainLoop(Client.java:242)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1566)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:537)
	at java.io.FileOutputStream.write(FileOutputStream.java:186)
	at zildo.fwk.file.EasyWritingFile.saveFile(EasyWritingFile.java:50)
	... 7 more
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Posix.writeBytes(Native Method)
	at libcore.io.Posix.write(Posix.java:223)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
	at libcore.io.IoBridge.write(IoBridge.java:532)
	... 9 more
```

We need to add an information, like for the corrupt saved games.

**Comment by tchegito** [comment]
[Fixed in 2.53]

85f5bd3b49264190901cdd45c6492638f9f993d7
