### ISSUE TITLE
NPE parsing float value in script

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#158]
Happened September 4th
```
version=v2.52
map=cavef7 (20x64)
sprites=[Perso=Zildo
Coords:(234.2608, 635.3372 0.0)
info=ZILDO
mvt=ATTAQUE_EPEE pv=12 weapon=[MIDSWORD,0] name=Duke lasthit=null, 234.2608, 645.3372 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 250.2608, 636.3372 (105 - bank 0), Entity id=47
x=146.0
y=587.0
nSpr=22
visible=true, Entity id=48
x=52.0
y=592.0
nSpr=25
visible=true, Entity id=49
x=64.0
y=592.0
nSpr=26
visible=true, Entity id=50
x=92.0
y=592.0
nSpr=25
visible=true, door1
160.0, 494.0 (2 - bank 5), door2
160.0, 434.0 (2 - bank 5), Entity id=53
x=158.0
y=340.0
nSpr=22
visible=true, Perso=new
Coords:(186.77516, 520.80426 0.0)
info=ENEMY
mvt=VIDE pv=2, 0.0, 0.0 (80 - bank 0), 181.80789, 518.30774 (104 - bank 4), 178.75027, 513.4697 (104 - bank 4), 194.02188, 527.4153 (104 - bank 4), 187.4636, 532.8339 (104 - bank 4)]
persos=[Perso=Zildo
Coords:(234.2608, 635.3372 0.0)
info=ZILDO
mvt=ATTAQUE_EPEE pv=12 weapon=[MIDSWORD,0] name=Duke lasthit=null, Perso=new
Coords:(186.77516, 520.80426 0.0)
info=ENEMY
mvt=VIDE pv=2]
variables={loc:94=0.0, loc:93=0.0, fishWater=6.0, bossFighting=0.0, moneyStolen=918.0, Carlo=[[MOON,1],800,0], Dizzie=[[DYNAMITE,1],15,0], BilelIgorVillage=[[DYNAMITE,1],100,0], loc:1=39.0, BOSS_turret_phase=1.0, nettleCount=-1, allowedDynamite=yes}
scripts=1 scripts running {[@scene@cavef7_lever[0 on [exec activeLever(15,39) , activate door1 , activate door2 ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, v3_crate, voleursm4_hiddenbutton, voleursm4_button, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_cell1kill, prison5_cell2kill, prison5_bigrat2kill, prison5_button1, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4_left, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, metKingPrison2, metKingPrison3, getMidSword, meetEleo, eleoSpeak, eleoWaitForVacto, startGatherNettle, eleog(13, 3), completeNettle1, completeNettle2, giveAntidote, vactoTriste, vactoToTheFarm, cavef2Hot, cavef6_button1, cavef7_lever, prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, foret(36, 30), bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, fermem2(7, 15), voleursg1(18, 4), voleursg3(3, 14), voleursg2(31, 24), voleursm2u(10, 7), voleursm3(8, 8), allFishMinsk, bucherons(12, 4), bucheronsg(30, 4), prison4r(9, 13), prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162, eleoforet1(57, 24), eleoforet2(27, 52), eleoforet2(16, 5), eleoforet2(28, 19), ferme(15, 59), eleoforet2(9, 61), eleoforet1(29, 9), eleoforet1(13, 20), sousbois6(21, 20), sousbois6(39, 34), sousbois3(39, 30), sousbois3(40, 30), sousbois1(15, 28), sousbois3(19, 4), sousbois3(14, 3), sousbois5(49, 13), sousbois5(54, 20), sousbois4(52, 13), sousbois4(30, 27), sousbois4(31, 29), antidotePrepared, voleurs(6, 36), voleursm5(12, 7), voleursm5(9, 7), voleurscave(44, 5), voleurscave(48, 5), voleurscave(48, 8), voleurscave(44, 8), voleurscave(3, 32), cavef1voleursg72]
lastdialog=Cave of the Flames
�Duke�: Ouah! It's really hot down there! Lava is very close.
Thieves Camp
It reads: <>
Clearing of the Oaks
Nature, Duke! Be aware!
Duke!
Nature, Duke! Be aware!
Duke!
Nature, Duke! Be aware!
Duke!
Nature, Duke! Be aware!
Duke!
Nature, Duke! Be aware!
Duke!
Lugdunia
Your two Half-moons have combined and you will now receive an additional Energy drop!
�Hezia�: Now, watch the show.
�Hezia�: Thanks for your money!
�Hezia�: Hi boy! My name is Hezia, the witch of the village. For 50 gold coins, I can increase your Energy.
Lugdunia Castle
�Duke�: It's just you and me, Dragon!
�Duke�: I need to go back into the Cave of the Flames, through that hole near the Thieves Camp.
Lugdunia Prison
�Maltus�: Of course, my King. Let us go immediately.
�King Trion�: Now, Maltus, will you get me out of here?
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:452)
	at zildo.fwk.script.logic.FloatVariable.evaluate(FloatVariable.java:85)
	at zildo.fwk.script.logic.FloatExpression.evaluate(FloatExpression.java:153)
	at zildo.fwk.script.model.point.PointEvaluator.getPoint(PointEvaluator.java:58)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:146)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:240)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:262)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:138)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:135)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:204)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by tchegito** [comment]
Hero is in downstairs the cave of the flames, at the floor of the dragon, in the room of the lever and key in the chest.
He happenened to go outside of the map, just below the wall near the lever. Maybe pushed by the firething ?
