### ISSUE TITLE
Still NPE on the waterlily

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#159]
(Happened 4 times during summer.)

Trace from'2018-07-31' \n

version=v2.52
map=igorlily (64x28)
sprites=[Perso=Zildo
Coords:(1004.0, 194.0 0.0)
info=ZILDO
mvt=TOUCHE pv=0 weapon=[SWORD,0] name=Link lasthit=null]
persos=[Perso=Zildo
Coords:(1004.0, 194.0 0.0)
info=ZILDO
mvt=TOUCHE pv=0 weapon=[SWORD,0] name=Link lasthit=null, Perso=new
Coords:(226.0, 172.0 10.0)
info=ENEMY
mvt=VIDE pv=2, Perso=new
Coords:(425.0, 221.0 10.0)
info=ENEMY
mvt=VIDE pv=2, Perso=new
Coords:(743.0, 408.0 10.0)
info=ENEMY
mvt=VIDE pv=2]
variables={nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], moneyStolen=176.0, BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2]}
scripts=2 scripts running {[death[3 on [herospecial 1 , music ZildoMort , fadeOut 5 , remove , filter 3 , fadeIn , sound ZildoDying , script zildo VIDE , angle zildo , wait 5 , angle zildo 1 , wait 5 , angle zildo 2 , wait 5 , angle zildo 3 , wait 5 , angle zildo , wait 5 , angle zildo 1 , wait 5 , angle zildo 2 , wait 5 , angle zildo 3 , wait 5 , angle zildo , wait 3 , angle zildo 1 , wait 4 , angle zildo 2 , perso zildo addSpr=0.0 , script zildo MORT , if hero_princess:1,0, wait 59 , fadeOut , end 1 ]],dieInWater[7 on [animation zildo.fwk.script.model.point.PointEvaluator@e951a18 WATER_SPLASH , sound ZildoPlonge , perso zildo addSpr=-1.0 , wait 10 , visible zildo , wait 40 , herospecial 1 5 , fadeOut 5 , perso zildo addSpr=-1.0 , focus zildo , actions]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, fermierperdu_ask, fermierperdu, fermierperdu_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, voleursm4_hiddenbutton, voleursm4_button, beenFishermanVillage, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, ask_visitprison, igor_promise_sword, prison4_openDoors, fermem2(7, 15), prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), voleursg3(3, 14), voleurscave(44, 5), voleurscave(44, 8), voleurscave(48, 8), voleurscave(48, 5), voleurscave(3, 32), voleursm2u(10, 7)]
lastdialog=Lugdunia
�Robert�: Please let me get some rest. I'll see you later.
�Robert�: If you're looking for my brother, Gerard, he's in his home.
�Robert�: Hi Link. As you can see, I'm exhausted from my work. There is always more work to do around here!
�Link�: Thanks. I'm on my way to meet this inventor.
�Anselme�: East of the woodcutters forest.
�Link�: It might be what we need. Where is this place?
�Anselme�: It seems to me that an inventor on the Fishermen Islands can blast through a wall, even a thick one.
�Hector�: Unfortunately, you're the only one of us allowed inside the jail, without alerting the black guards.
�Link�: But how can we get him out of there?
�Anselme�: This boy's suggestion sounds really promising.
�Hector�: Very good. As weird as it sounds for us, we have to get him out of the jail.
�Link�: There's a blacksmith in jail, named Igor. He said he could enhance my Sword to make it efficient against black guards.
�Hector�: Speak, Link, we're listening carefully.
�Link�: I may have a solution.
�Hector�: We have to find a way to defeat them.
�Hector�: He's most likely in there. And probably a black guard nearby holds the key.
�Link�: Unfortunately, I haven't found our King. But there's a locked door that I couldn't access.
�Hector�: Link, at last! So what did you find?
�Citizen�: Hi little boy! Aren't you too young to hang out in here?
�Citizen�: Rumor has it weird monsters are prowling around Fishermen Island.
java.lang.NullPointerException: Attempt to invoke virtual method 'zildo.monde.util.Point zildo.monde.map.Area.getNextMapOffset(zildo.monde.map.Area, zildo.monde.util.Angle, boolean)' on a null object reference
	at zildo.server.MapManagement.shiftPreviousMap(MapManagement.java:836)
	at zildo.server.MapManagement.processChangingMap(MapManagement.java:703)
	at zildo.server.EngineZildo.renderEvent(EngineZildo.java:224)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:157)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by tchegito** [comment]
Same symptom than #125 and #143, but different cause indeed.

**Comment by tchegito** [comment]
[Fixed in 2.53]

coeff were adjusted. All tests are ok: fingers crossed !

dab2cbcf2a8040c3cbbf031d410527d9747bdd54
