### ISSUE TITLE
NPE in PathFinder

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#172]
Happened 27/01/2019

```
version=v2.55
map=eleom1 (20x15)
sprites=[Perso=Zildo
Coords:(74.638214, 78.233955 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=[MIDSWORD,0] name=Lunge lasthit=last hit by Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois7, 74.638214, 88.233955 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 159.01282, 117.35206 (103 - bank 0), Entity id=322
x=229.0
y=61.0
nSpr=201
visible=true, 229.0, 51.0 (CANDLE1), Entity id=324
x=40.0
y=136.0
nSpr=161
visible=true, Entity id=325
x=140.0
y=107.0
nSpr=211
visible=true, 56.0, 96.0 (BARREL), Entity id=327
x=60.0
y=78.0
nSpr=3
visible=true, Entity id=328
x=57.0
y=79.0
nSpr=159
visible=true, Perso=eleoric
Coords:(88.0, 80.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), Perso=new
Coords:(257.0, 75.0 0.0) ==> (260,75)
info=SHOOTABLE_NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 257.0, 74.0 (SHADOW_SMALL), 88.0, 42.0 (CAULDRON1), bag
161.0, 113.0 (EMPTY_BAG)]
persos=[Perso=Zildo
Coords:(74.638214, 78.233955 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=[MIDSWORD,0] name=Lunge lasthit=last hit by Perso=new
Coords:(309.0, 365.0 0.0)
info=ENEMY
mvt=VIDE pv=1 on sousbois7, Perso=eleoric
Coords:(88.0, 80.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=new
Coords:(257.0, 75.0 0.0) ==> (260,75)
info=SHOOTABLE_NEUTRAL
mvt=VIDE pv=1]
variables={loc:24=0.0, loc:23=0.0, allowedDynamite=yes, nettleCount=-1, loc:187=0.0, loc:1=tortueSousbois7_2, moneyStolen=144.0, loc:60=0.0, loc:59=0.0, BilelIgorVillage=[[EMPTY_BAG,1],100,2],[[DYNAMITE,1],100,0], loc:188=0.0, Carlo=[[MOON, 1], 800, 1], bossFighting=0.0, loc:0=tortueSousbois7, Dizzie=[[DYNAMITE, 1], 15, 20], BOSS_turret_phase=0.0, fishWater=6.0}
scripts=2 scripts running {[@scene@eleoWaitForVacto[0 on [exec vactoComeIn ]],fromActions[0 on [timer ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, fermierperdu_ask, fermierperdu, fermierperdu_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, voyante, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, v3_crate, voleursm4_hiddenbutton, voleursm4_button, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, ask_visitprison, igor_promise_sword, prison4_openDoors, prison5_bigrat2kill, prison5_button1, prison5_button2, p5_trigger_smoke, p6_trigger_smoke, prison7(22, 11), prison4l(9, 13), prison5(9, 2), zildoAccessIgor, waitIgor, freedIgor, meetLib1, getBackIgor, roxyMeetIsidore, wow_1, wow_2, wow_3, wow_4, jump_stumpNature3, jump_stumpNature2, jump_stumpNature1, sousbois4, sousbois4SeeFireflies, killGard1, prison10Button, prison12Locked, boss_turret, fightBossTurret1, killBossTurret1, prison15Interrogation, metKingPrison, killKingGuards, getMidSword, meetEleo, eleoSpeak, eleoWaitForVacto, fermem2(7, 15), prisonext(40, 40), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, foret(36, 30), voleursg1(18, 4), voleursg2(31, 24), voleursm2u(10, 7), voleurscave(48, 5), voleurscave(48, 8), voleurscave(44, 8), voleurscave(44, 5), voleurscave(3, 32), voleursm3(8, 8), allFishMinsk, prison(6, 2), secretDoorRevealed, waitingForIgor, jump_stumpNatureReady, prisonnoirKEY, prisonprison82, prison11(9, 3), prison12prison92, fromPrison13, prison16noir1KEY, chateausudprison162]
lastdialog=Silver Forest
�Vacto�: Very well, druid. See you tomorrow.
�Eleoric�: Thank you Vacto, you can leave now.
�Eleoric�: About time! We are only missing nettle leaves for the King's remedy!
�Vacto�: I brought hellebore seeds, some bat tears, and obsidian.
�Eleoric�: So, what did you find today?
�Vacto�: Hi.
�Eleoric�: This is Vacto, my assistant.
�Vacto�: Greetings druid, I've come back from harvesting.
�Eleoric�: Come in!
�Eleoric�: I need hellebore seeds, bat tears, nettle leaves, and obsidian.
�Eleoric�: The thing is, to prepare a potion for hay fever, I need a lot of ingredients.
�Eleoric�: You are Lunge and come for a remedy? You knocked at the right door.
�Eleoric�: Greetings young man! My name is Eleoric, druid of the Silver Birch Forest.
North - Silver Forest. South - Oaks Forest. East - Lugdunia Castle.
Lugdunia Castle
�Irma�: I'd like to regain a little bit of peace.
�Irma�: I live with my grandson in the Silver Birch Forest. But he refuses to leave since he works with that druid.
�Irma�: This park used to be highly frequented before. But since the castle has expanded, there are not many roads leading here anymore.
�Irma�: Well, it's not often I see new people around here!
Lugdunia Prison
�Lunge�: Alright, your Highness, I'm going to face them.
�King Trion�: So take care of them, and I will follow you once it is done.
java.lang.NullPointerException: Attempt to read from field 'int zildo.monde.util.Point.x' on a null object reference
	at zildo.monde.sprites.persos.ia.PathFinder.collide(PathFinder.java:267)
	at zildo.monde.sprites.persos.PersoNJ.move(PersoNJ.java:420)
	at zildo.monde.sprites.persos.PersoNJ.animate(PersoNJ.java:193)
	at zildo.server.SpriteManagement.updateSprites(SpriteManagement.java:607)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:228)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1583)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
```

**Comment by tchegito** [comment]
Happened again (27/01/2019):

```
version=v2.62
map=promenade2 (64x32)
sprites=[Perso=Zildo
Coords:(577.0, 169.0 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[SWORD,0] name=az lasthit=last hit by Perso=new
Coords:(779.9202, 48.519997 1.2) ==> (887.7523,4.427413)
info=ENEMY
mvt=TOUCHE pv=1 on promenade, 578.0, 179.0 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 555.8574, 397.6432 (103 - bank 0), 691.0, 540.0 (116 - bank 0), 691.0, 540.0 (115 - bank 0), Perso=new
Coords:(-99.5, 382.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, -304.5, 521.0 (80 - bank 0), -99.5, 381.0 (SHADOW_SMALL), Perso=new
Coords:(-100.0, 489.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, -306.0, 682.0 (80 - bank 0), -100.0, 488.0 (SHADOW_SMALL), Perso=new
Coords:(1123.5, 252.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, 1528.5, 326.0 (80 - bank 0), 1123.5, 251.0 (SHADOW_SMALL), Perso=new
Coords:(-100.0, 134.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, -306.0, 149.0 (80 - bank 0), -100.0, 133.0 (SHADOW_SMALL), Perso=new
Coords:(-99.5, 421.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, -304.5, 580.0 (80 - bank 0), -99.5, 420.0 (SHADOW_SMALL), Perso=new
Coords:(405.29913, 256.91266 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 405.29913, 255.91266 (SHADOW), Perso=emissaire
Coords:(455.0, 256.0 0.0)
info=null
mvt=null pv=2, 0.0, 0.0 (80 - bank 0), 0.0, -12.0 (116 - bank 2), Perso=tony
Coords:(455.0, 215.0 0.0)
info=null
mvt=null pv=1, 0.0, 0.0 (80 - bank 0), Perso=roxy_bunny
Coords:(400.8435, 245.74695 4.9999986)
info=null
mvt=null pv=1, 0.0, 0.0 (80 - bank 0), 400.8435, 244.74695 (SHADOW_SMALL)]
persos=[Perso=Zildo
Coords:(577.0, 169.0 0.0)
info=ZILDO
mvt=VIDE pv=7 weapon=[SWORD,0] name=az lasthit=last hit by Perso=new
Coords:(779.9202, 48.519997 1.2) ==> (887.7523,4.427413)
info=ENEMY
mvt=TOUCHE pv=1 on promenade, Perso=new
Coords:(-99.5, 382.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, Perso=new
Coords:(-100.0, 489.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, Perso=new
Coords:(1123.5, 252.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, Perso=new
Coords:(-100.0, 134.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, Perso=new
Coords:(-99.5, 421.0 40.41733)
info=NEUTRAL
mvt=VIDE pv=2, Perso=new
Coords:(405.29913, 256.91266 0.0)
info=NEUTRAL
mvt=VIDE pv=1, Perso=emissaire
Coords:(455.0, 256.0 0.0)
info=null
mvt=null pv=2, Perso=tony
Coords:(455.0, 215.0 0.0)
info=null
mvt=null pv=1, Perso=roxy_bunny
Coords:(400.8435, 245.74695 4.9999986)
info=null
mvt=null pv=1]
variables={BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2], nettleCount=-1, Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE, 1], 15, 20], allowedDynamite=yes, allowedTakeFork=no}
scripts=1 scripts running {[@scene@trig_echange[5 on [speak zildo promenade2.zildo.pret , moveTo zildo (32, -32) , fadeOut , wait 20 , moveTo zildo (0, 0) , exec echange , exec intro_episode2 ]],}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, voyante, talk_about_witch, talk_about_witch2, tonneau_polakyg, fermem2(7, 15), prisonext(40, 40), foret(36, 30), trip_polaky, polaky3(2, 7), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, sorciere_once]
lastdialog=
�Clairière des chênes�
�Garde�: Princesse Roxy !!!
�Princesse Roxy�: Euh ... je ne sais pas. C'est ... euh
�Garde�: Helios soit loué ! Vous allez bien princesse ?
�Princesse Roxy�: Où suis-je ? C'est toi grand-père ?
�Bandit�: Je vais lui donner la potion que m'a remis mon maître.
�Garde�: Alors réveillez la ! Et vite !
�Bandit�: Elle a été ensorcelée pour dormir.
�Garde�: Qu'est ce que vous lui avez fait ?
�Garde�: J'aurais bien aimé, mais je ne sais pas d'où il vient !
�Bandit�: Vous m'avez piégé avec ce vautour !
�Bandit�: Qu'est ce que c'est ?!?
�Bandit�: Quand j'aurais le sceptre, elle se réveillera.
�Garde�: Est-ce qu'elle va bien ?
�Bandit�: Reculez maintenant.
�Bandit�: Amenez le sceptre qu'on en finisse.
�Bandit�: La fille est ici.
L'heure du rendez-vous à la promenade est enfin arrivée.
�Az�: Je vais me cacher derrière ces arbres, en attendant minuit.
�Forêt de Lugdunia�
Clairière des chênes au sud.
�Maltus�: Bonne chance az.
java.lang.NullPointerException: Attempt to read from field 'float zildo.monde.util.Pointf.x' on a null object reference
	at zildo.monde.sprites.persos.ia.PathFinder.collide(PathFinder.java:285)
	at zildo.monde.sprites.persos.PersoNJ.move(PersoNJ.java:448)
	at zildo.monde.sprites.persos.PersoNJ.animate(PersoNJ.java:216)
	at zildo.monde.sprites.persos.PersoSquirrel.animate(PersoSquirrel.java:46)
	at zildo.server.SpriteManagement.updateSprites(SpriteManagement.java:615)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:228)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```
