### ISSUE TITLE
NPE on CrashReport

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#176]
version=v2.55
```
map=d5m1 (20x15)
sprites=[]
persos=[]
variables={BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2], nettleCount=-1, Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE, 1], 15, 20], allowedDynamite=yes}
scripts=0 scripts running {[}
quests=[]
lastdialog=Lugdunia
�Gerard�: Hi, my name's Gerard. You must be Денис, Renaldo's son. What can I do for you?
[2.55] 09/07/2019

�Princess Roxy�: At his house, follow me.
�ÐÐµÐ�: Alright, I would be glad to help him. Where is he?
�Princess Roxy�: Hello Денис. I think that my grandfather has a favor to ask of you.
�ÐÐµÐ�: Greetings Princess! What's happening in the village?
Once upon a time in Alembrume, around the peaceful homes of Lugdunia Village...
java.lang.IndexOutOfBoundsException: Index: 315, Size: 220
	at java.util.ArrayList.get(ArrayList.java:437)
	at zildo.fwk.bank.SpriteBank.get_sprite(SpriteBank.java:122)
	at zildo.client.gui.GUIDisplay.prepareTextInFrame(GUIDisplay.java:490)
	at zildo.client.gui.GUIDisplay.displayTexter(GUIDisplay.java:761)
	at zildo.client.stage.TexterStage.renderGame(TexterStage.java:54)
	at zildo.platform.opengl.AndroidOpenGLGestion.render(AndroidOpenGLGestion.java:410)
	at zildo.client.Client.render(Client.java:273)
	at zildo.client.Client.mainLoop(Client.java:233)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
```

Clue: player's name seems to have cyrillic characters

**Comment by tchegito** [comment]
Happens again the same day:

```
version=v2.55
map=d5m1 (20x15)
sprites=[Perso=Zildo
Coords:(68.14661, 106.98603 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=null name=Денис lasthit=null, 69.14661, 116.98603 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 691.0, 540.0 (102 - bank 0), Entity id=17
x=80.0
y=24.0
nSpr=161
visible=true, Entity id=18
x=176.0
y=24.0
nSpr=161
visible=true, Entity id=19
x=80.0
y=152.0
nSpr=161
visible=true, Entity id=20
x=176.0
y=152.0
nSpr=161
visible=true, Perso=gerard
Coords:(120.0, 72.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 120.0, 71.0 (SHADOW)]
persos=[Perso=Zildo
Coords:(68.14661, 106.98603 0.0)
info=ZILDO
mvt=VIDE pv=5 weapon=null name=Денис lasthit=null, Perso=gerard
Coords:(120.0, 72.0 0.0)
info=NEUTRAL
mvt=VIDE pv=1]
variables={BilelIgorVillage=[[EMPTY_BAG, 1], 100, 2], [[BLUEDROP, 1], 15, -1], [[DYNAMITE, 1], 100, 2], nettleCount=-1, Carlo=[[MOON, 1], 800, 1], Dizzie=[[DYNAMITE, 1], 15, 20], allowedDynamite=yes}
scripts=0 scripts running {[}
quests=[]
lastdialog=Lugdunia
�Gerard�: Hi, my name's Gerard. You must be Денис, Renaldo's son. What can I do for you?
�Princess Roxy�: At his house, follow me.
�ÐÐµÐ�: Alright, I would be glad to help him. Where is he?
�Princess Roxy�: Hello Денис. I think that my grandfather has a favor to ask of you.
�ÐÐµÐ�: Greetings Princess! What's happening in the village?
Once upon a time in Alembrume, around the peaceful homes of Lugdunia Village...
java.lang.IndexOutOfBoundsException: Index: 315, Size: 220
	at java.util.ArrayList.get(ArrayList.java:437)
	at zildo.fwk.bank.SpriteBank.get_sprite(SpriteBank.java:122)
	at zildo.client.gui.GUIDisplay.prepareTextInFrame(GUIDisplay.java:490)
	at zildo.client.gui.GUIDisplay.displayTexter(GUIDisplay.java:761)
	at zildo.client.stage.TexterStage.renderGame(TexterStage.java:54)
	at zildo.platform.opengl.AndroidOpenGLGestion.render(AndroidOpenGLGestion.java:410)
	at zildo.client.Client.render(Client.java:273)
	at zildo.client.Client.mainLoop(Client.java:233)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1271)
```
