### ISSUE TITLE
NPE since 2.56 on isMultifloor

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#177]
```
version=v2.56
map=prison4r (20x15)
sprites=[Perso=Zildo
Coords:(151.1514, 184.90417 0.0)
info=ZILDO
mvt=VIDE pv=8 weapon=[DYNAMITE,1] name=Steff lasthit=last hit by Perso=new
Coords:(74.56, 206.67984 7.6999993) ==> (156.0204,163.0)
info=ENEMY
mvt=TOUCHE pv=1 on buchforet, 152.1514, 194.90417 (80 - bank 0), 691.0, 540.0 (83 - bank 0), 691.0, 540.0 (SHADOW), 160.8516, 186.47446 (103 - bank 0), 691.0, 540.0 (116 - bank 0), 691.0, 540.0 (115 - bank 0), 224.0, 64.0 (BARREL), 216.0, 80.0 (BARREL), 208.0, 64.0 (BARREL), 192.0, 64.0 (BARREL), Entity id=62
x=248.0
y=144.0
nSpr=200
visible=true, Entity id=63
x=256.0
y=160.0
nSpr=200
visible=true, 240.0, 160.0 (CRATE), Perso=new
Coords:(233.498, 125.25005 0.0)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 233.498, 124.25005 (SHADOW_SMALL), Perso=new
Coords:(128.78407, 50.84649 0.0) ==> (128.78407,48.603813)
info=ENEMY
mvt=VIDE pv=1, 0.0, 0.0 (80 - bank 0), 128.78407, 49.84649 (SHADOW_SMALL), 152.0, 196.0 (SHADOW_SMALL), 152.0, 197.0 (DYNAMITE), 144.0, 196.0 (EXPLO1), 159.0, 196.0 (EXPLO1), 159.0, 211.0 (EXPLO1), 144.0, 211.0 (EXPLO1)]
persos=[Perso=Zildo
Coords:(151.1514, 184.90417 0.0)
info=ZILDO
mvt=VIDE pv=8 weapon=[DYNAMITE,1] name=Steff lasthit=last hit by Perso=new
Coords:(74.56, 206.67984 7.6999993) ==> (156.0204,163.0)
info=ENEMY
mvt=TOUCHE pv=1 on buchforet, Perso=new
Coords:(233.498, 125.25005 0.0)
info=ENEMY
mvt=VIDE pv=1, Perso=new
Coords:(128.78407, 50.84649 0.0) ==> (128.78407,48.603813)
info=ENEMY
mvt=VIDE pv=1]
variables={Dizzie=[[DYNAMITE,1],15,12], allowedDynamite=yes, allowedTakeFork=no, BilelIgorVillage=[[DYNAMITE,1],100,1], fishWater=6.0, nettleCount=-1, Carlo=[[MOON, 1], 800, 1], moneyStolen=216.0}
scripts=0 scripts running {[}
quests=[flut_ask, flut, chateau_ask, enlevebuissons, enlevebuissons_win, gardelaitier, gardelaitier_win, ritou_bar, enlevement, hector_1, start_defi1, stop_defi1, start_visit1, suite_visit1_weapon, maltus_foret, maltus_foret_zildo_defeat, foretg_button_trig, foretg_apres_grotte, bosquet_kill_gards, bosquet_free_way, polaky_greg, zildo_polaky_killguards, zildo_polaky, foret_back, start_visit2, trig_echange, voyante, tonneau_polakyg, fuite_tony1, vert_seen, attaque_voleurs, beanCaveFlames, meanwhile_voleurs, voleursm2u(4, 3), voleursm4(13, 3), trig_falcor, v3_crate, beenFishermanVillage, minsk_fishes, rewardMinsk, cheapDynamite, takeSawdust, giveSawdust, borisWait, backCoucou, retour_trion, zildoDream, hector_call1, hector_call2, hector_call3, forbid_dynamiteCell, ask_visitprison, igor_promise_sword, prison4_doors, paid_gard, prison4_openDoors, prison5_bigrat2kill, prison5_button1, prison5_button2, prison4l(9, 13), prison5(9, 2), fermem2(7, 15), prisonext(40, 40), trip_polaky, polaky3(2, 7), foret(36, 30), bosquetbosquetm2, bosquetm77KEY, bosquetmbosquetm22, polaky4(27, 19), polaky4(31, 19), polakyg3polakyg42, voleursg1(18, 4), voleursg3(3, 14), voleursm2u(10, 7), voleursm3(8, 8), allFishMinsk, prison4r(9, 13)]
lastdialog=Prison de Lugdunia
�Grand-père�: Bonne chance mon bon Steff ! Et ne t'inquiètes pas pour moi !
�Grand-père�: Essaie par exemple d'en jouer là où ma petite fille a disparu. Et à d'autres endroits également, elle te sera très utile, j'en suis sûr.
�Grand-père�: Et si tu ne sais plus quoi faire, sache que la flûte que tu as avec toi a des pouvoirs. Elle communique avec la nature d'Alembrume.
�Grand-père�: De toute façon, il ne faut pas s'occuper d'un vieillard comme moi ! Steff, je te demande plutôt de retrouver ma petite Roxy !
�Grand-père�: Je ne sais pas combien de temps ils vont me garder ici, mais j'ai l'impression que les gardes ne sont plus les mêmes. Je ne vois plus la bienveillance que je leur connaissais.
�Grand-père�: Mais les gardes ont dû me trouver trop véhément, et m'ont conduit en prison pour trouble à l'ordre public.
�Grand-père�: Je ne supportais plus de savoir ma fille enlevée, et ne te voyant pas revenir, je me suis rendu au château pour obtenir un entretien avec le Roi.
�Grand-père�: Ah mon pauvre Steff ! Te voici ! Dans quel état tu me trouves ...
�Garde�: Allez petit, je te surveille !
�Steff�: Allez petit, je te surveille !
�Igor�: En échange, je pourrais améliorer ton épée, qui m'a l'air un peu rustique.
�Igor�: Tu peux te rendre à mon village, à l'est de la forêt des bûcherons de Lugdunia. Mais il faudra trouver un autre moyen de franchir la rive !
�Igor�: En échange, je pourrais améliorer ton épée, qui m'a l'air un peu rustique.
�Igor�: Avec de la dynamite, tu pourrais faire sauter le mur. De l'autre côté évidemment, sinon les gardes t'attraperaient aussitôt.
�Igor�: Regarde ce mur derrière moi, mais discrètement. Ca fait une semaine que je suis ici, et je creuse doucement avec une petite cuillère.
�Igor�: Tu es interessé par de la dynamite ? Avec, tu pourrais me faire sortir de prison par exemple.
�Igor�: Et les gardes m'ont attrapé juste après l'explosion. Il faut dire que ce n'est pas dans mes habitudes de faire ça, je ne suis qu'un modeste forgeron !
�Igor�: Comme les voleurs n'arrêtaient pas de venir chaparder nos poissons, j'ai fini par faire sauter le pont qui mène à l'île de notre village avec de la dynamite.
�Igor�: Mais est-ce bien un endroit pour un jeune garçon ? Oh je ne suis pas un bandit, tu n'as rien à craindre de moi.
�Igor�: Bonjour petit, je suis Igor, le forgeron du village des pêcheurs.
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
	at zildo.monde.collision.Collision.isMultifloor(Collision.java:80)
	at zildo.server.CollideManagement.checkZildoWound(CollideManagement.java:233)
	at zildo.server.CollideManagement.checkAllZildoWound(CollideManagement.java:179)
	at zildo.server.CollideManagement.manageCollisions(CollideManagement.java:117)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:230)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:194)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:116)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)
```

**Comment by tchegito** [comment]
Fixed in [2.57]

065c4fe7cad4e0054d5132aa9705134c32a22cba
