### ISSUE TITLE
Exception reported on GooglePlay (Nullpointer in ActionExecutor.render)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tchegito/zildo#45]
```
Version 1.6:

java.lang.NullPointerException
at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:171)
at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:141)
at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:78)
at zildo.server.state.ScriptManagement.render(ScriptManagement.java:91)
at zildo.server.EngineZildo.renderFrame(EngineZildo.java:179)
at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:162)
at zildo.client.Client.mainLoop(Client.java:170)
at com.zildo.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:102)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1363)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1118)
```

Original issue reported on code.google.com by `tcheg...@gmail.com` on 15 Sep 2012 at 11:07

**Comment by tchegito** [comment]
Still present, despite an effort to add details to exception:

java.lang.RuntimeException: 
   at zildo.fwk.script.command.ActionExecutor.render (ActionExecutor.java:163)
   at zildo.fwk.script.command.ScriptExecutor.renderAction (ScriptExecutor.java:233)
   at zildo.fwk.script.command.ScriptExecutor.renderElement (ScriptExecutor.java:255)
   at zildo.fwk.script.command.ScriptExecutor.render (ScriptExecutor.java:133)
   at zildo.server.state.ScriptManagement.render (ScriptManagement.java:130)
   at zildo.server.EngineZildo.renderFrame (EngineZildo.java:195)
   at zildo.client.stage.SinglePlayer.updateGame (SinglePlayer.java:172)
   at zildo.client.Client.mainLoop (Client.java:193)
   at com.alembrum.OpenGLRenderer.onDrawFrame (OpenGLRenderer.java:105)
   at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1649)
   at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1354)

Above stacktrace is from version 2.30, and still unresolved ...

**Comment by tchegito** [comment]
With my "CrashReporter" I managed to fetch the complete message:

java.lang.RuntimeException: We need valid 'who' or 'what' attribute in action pos barrel1 (0, 16) 
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:163)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:196)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1565)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1277)

That surely will help.

**Comment by tchegito** [comment]
With more details from CrashReporter, it appears that the situation is as follows:
- hero is on the map just after the door (polakyg3)
- he's being pushed by a guard hitting him
- when he arrives in "polakyg" we got the exception

**Comment by tchegito** [comment]
Same kind of problem, but different situation: (notice hero is dead)

map=sousbois6 (64x45)
sprites=[Perso=Zildo
Coords:(619.5853, 414.46887 0.0)
info=ZILDO
mvt=MORT]
persos=[Perso=Zildo
Coords:(619.5853, 414.46887 0.0)
info=ZILDO
mvt=MORT]
variables={fishWater=6.0, nettleCount=-1, Carlo=[[MOON, 1], 800, 1], allowedDynamite=yes, Dizzie=[[DYNAMITE, 1], 15, 20], moneyStolen=371.0, BilelIgorVillage=[[EMPTY_BAG,1],100,1]}
java.lang.RuntimeException: We need valid 'who' or 'what' attribute in action moveTo wow (50, 40) circular 
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:163)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:230)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:257)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:133)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:130)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:196)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:172)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:107)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1648)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1353)
