### ISSUE TITLE
NPE in 2.20

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#78]
3 crash in December

java.lang.NullPointerException
	at zildo.client.stage.TexterStage.<init>(TexterStage.java:32)
	at zildo.client.gui.menu.CompassMenu$2.run(CompassMenu.java:25)
	at zildo.client.Client.mainLoop(Client.java:230)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1464)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1218)

It means that there's no Game object in EngineZildo. Only possibility is: player is still at the main menu phase, with no game started.

**Comment by tchegito** [comment]
Fixed in 2.21.

Actually, "Compass" menu was reachable at the main menu. This was totally nonsense. Now it's ok.
