### ISSUE TITLE
[2.24] Crash when restoring game first time

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#84]
Player was throwing a hen at the very beginning, and falling into water. So game should restart, and respawn him at his previous location. Instead of this, we got following exception:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.ByteBuffer zildo.fwk.file.EasyBuffering.getAll()' on a null object reference
	at zildo.server.EngineZildo.restoreBackedUpGame(EngineZildo.java:289)
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:526)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:212)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:236)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:207)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:236)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:120)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:128)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:189)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:167)
	at zildo.client.Client.mainLoop(Client.java:192)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)

**Comment by tchegito** [comment]
Fixed in 2.25 (by adding an automatic quicksave at end of 'intro' script)

https://github.com/tchegito/zildo/commit/bba4feb841a80587f7ebfc815d07bda87698f350
