### ISSUE TITLE
[2.24] Crash pressing button

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#85]
java.lang.NullPointerException: Attempt to invoke virtual method 'void zildo.platform.input.AndroidInputInfos.pressButton(zildo.platform.input.AndroidKeyboardHandler$KeyLocation)' on a null object reference
	at com.alembrum.TouchListener.pressGameButton(TouchListener.java:172)
	at com.alembrum.ZildoActivity.handleKeys(ZildoActivity.java:227)
	at com.alembrum.ZildoActivity.onKeyDown(ZildoActivity.java:203)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2645)
	at android.app.Activity.dispatchKeyEvent(Activity.java:2748)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2307)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4384)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4340)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4018)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4075)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4221)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:148)
	at android.os.Looper.loop(Looper.java:151)
	at android.app.ActivityThread.main(ActivityThread.java:5576)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

**Comment by tchegito** [comment]
Fixed in 2.25 (similar to #37)

https://github.com/tchegito/zildo/commit/5a82a4847ae2d898d098693faeeef7ca2b6298ca
