### ISSUE TITLE
[2.27] Exception when hero hit enemy with a bush

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#87]
java.lang.NullPointerException: Attempt to read from field 'zildo.monde.items.ItemKind zildo.monde.items.Item.kind' on a null object reference
	at zildo.server.CollideManagement.hit(CollideManagement.java:234)
	at zildo.server.CollideManagement.checkEnemyWound(CollideManagement.java:195)
	at zildo.server.CollideManagement.manageCollisions(CollideManagement.java:97)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:195)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:167)
	at zildo.client.Client.mainLoop(Client.java:192)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by tchegito** [comment]
Fixed in 2.28:
ae35fb72892255578ec586d5d7fe42707db4ffe5
