### ISSUE TITLE
[2.28] Exception on cutscene

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#90]
Report from player:
game always stop @ under the bridge of fishermen's ville

java.lang.RuntimeException: We need valid 'who' or 'what' attribute in action moveTo vert (-30, 0) 
	at zildo.fwk.script.command.ActionExecutor.render(ActionExecutor.java:157)
	at zildo.fwk.script.command.ScriptExecutor.renderAction(ScriptExecutor.java:213)
	at zildo.fwk.script.command.ScriptExecutor.renderElement(ScriptExecutor.java:235)
	at zildo.fwk.script.command.ScriptExecutor.render(ScriptExecutor.java:120)
	at zildo.server.state.ScriptManagement.render(ScriptManagement.java:129)
	at zildo.server.EngineZildo.renderFrame(EngineZildo.java:189)
	at zildo.client.stage.SinglePlayer.updateGame(SinglePlayer.java:167)
	at zildo.client.Client.mainLoop(Client.java:193)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by tchegito** [comment]
This is same as issue 74, but this time we have context.

Hero is crossing the bridge near the thieves camp, and we try to move character named 'vert'. Apparently, he's not found on this game.
Maybe first time, hero managed to pass here without triggering the quest ? We have this:
`<location name="voleurs" pos="612,830" radius="2"/>`

We should try to do that: pass without triggering this, and if it's possible, we must increase radius.
And as a workaround for players passing second time, and always getting the exception, we must check if 'vert' exists. With 'lookFor' maybe ?

**Comment by tchegito** [comment]
Fixed in 2.29

Two actions:
- detect if "vert" exists to avoid an NPE
- replace the spot in order to player ALWAYS trigger the quest

0933d58cc16ef4ee2734e607841f0b7c535216b6
