### ISSUE TITLE
[2.28] Exception on loading

### ISSUE THREAD

**Issue by tchegito** [tchegito/zildo#91]
java.lang.RuntimeException: Impossible to replace Zildo !Was on coucou original position: (120.0, 384.0)
	at zildo.server.MapManagement.arrangeLocation(MapManagement.java:1031)
	at zildo.client.gui.menu.SaveGameMenu.loadGameFromBuffer(SaveGameMenu.java:176)
	at zildo.client.gui.menu.SaveGameMenu.loadGame(SaveGameMenu.java:144)
	at zildo.client.gui.menu.SaveGameMenu.access$2(SaveGameMenu.java:141)
	at zildo.client.gui.menu.SaveGameMenu$2.run(SaveGameMenu.java:86)
	at zildo.client.Client.mainLoop(Client.java:234)
	at com.alembrum.OpenGLRenderer.onDrawFrame(OpenGLRenderer.java:105)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**Comment by tchegito** [comment]
Fixed in 2.29

We increase the number of try to determine a valid location for hero. But this isn't maybe uncrackable. For example, if player saves his game under a bush surrounded by many other. This need to be checked later in third episode 3.

8fe217cf5d29602a7b0f9be2766cd671be3fac17
